### PR TITLE
Human-readable column names in datamap response

### LINKED ISSUE #778: Provide human-readable values for data map item attributes
### Is your feature request related to a specific problem?

From a UI perspective, human readable values should be present in the api response for a datamap

### Describe the solution you'd like

Provide a mapping of data map item attributes to human readable names, either directly in the response of data item attributes or as a separate response object

### Describe alternatives you've considered, if any

Having the mapping/naming done in the UI

### Additional context

Currently the response is generated from the joined dataframes used to generate the records, via dot notation

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #778

### Code Changes

* [x] Update the `DATAMAP_COLUMNS` constant to be a dictionary for use within pandas as well as readable values
* [x] Update usage of `DATAMAP_COLUMNS` throughout codebase
* [x] Use `DATAMAP_COLUMNS` in testing
* [x] Duplicate the `dataset.name` column as `dataset.source_name` to maintain the current data map structure for an item

### Steps to Confirm

* [x] The response contains the column values when called manually
* [x] The response contains column names even when no other data is returned for the datamap

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [x] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [x] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] ~Update `CHANGELOG.md`~ not value added, iterative as part of original endpoint addition

### Description Of Changes

Further iterations to better define the API contract for use with the UI.

### CODE REVIEW

**Comment by SteveDMurphy** [comment]
@ThomasLaPiana @elliotbonneville I think this makes sense to ship as part of 1.7 (if we can) to stay ahead of any UI work, putting into review in current state and adding both of you as reviewers 👍🏽

**Review by ThomasLaPiana — APPROVED** [review]
LGTM! Just one question about another issue we might be able to open from this

**Comment by ThomasLaPiana** [comment]
@SteveDMurphy this is a great change, do you think it would be feasible to pop open another issue that pulls these human-readable names directly from the fideslang model? using the `alias` field of the `Field` class

Example:
```python
# Fides Base Model
class FidesModel(BaseModel):
    """The base model for all Fides Resources."""

    fides_key: FidesKey = Field(
        alias="Fides Key",
        description="A unique key used to identify this resource."
    )
```

then you could do something like:

`system.fides_key.alias` to get "Fides Key"

**Comment by SteveDMurphy** [comment]
> @SteveDMurphy this is a great change, do you think it would be feasible to pop open another issue that pulls these human-readable names directly from the fideslang model? using the `alias` field of the `Field` class
> 
> Example:
> 
> ```python
> # Fides Base Model
> class FidesModel(BaseModel):
>     """The base model for all Fides Resources."""
> 
>     fides_key: FidesKey = Field(
>         alias="Fides Key",
>         description="A unique key used to identify this resource."
>     )
> ```
> 
> then you could do something like:
> 
> `system.fides_key.alias` to get "Fides Key"
> 
> The human-readable values you added are great documentation, so I think it'd be beneficial to integrate them into the models themselves

I'm a big fan of this @ThomasLaPiana, great suggestion 🙌🏽 just to clarify, we want to write this issue up as adding a new data map model for the data map to replace the constant used in here, correct?

Also just for reference, #793 was opened up yesterday to potentially modify the output

**Comment by SteveDMurphy** [comment]
Requested to keep this open a bit longer in case of any further required changes

**Comment by SteveDMurphy** [comment]
Okay, thanks for the clarification @ThomasLaPiana 👍🏽  
Currently there is a bit of separation between columns in the Pandas DataFrame and the pydantic models it is built from so will do some research into that when creating the issue

**Comment by ThomasLaPiana** [comment]
> Okay, thanks for the clarification @ThomasLaPiana 👍🏽 Currently there is a bit of separation between columns in the Pandas DataFrame and the pydantic models it is built from so will do some research into that when creating the issue

Ah i see, ok we can hash it out in the issue 🙂

**Comment by SteveDMurphy** [comment]
[fideslang#57](https://github.com/ethyca/fideslang/issues/57) created for aliasing, thanks again for the highlighting the need/benefits of doing that @ThomasLaPiana !

**Pull request merged**
