### PR TITLE
Bump python version from 3.10.7 to 3.10.11

### PR DESCRIPTION
**Pull request by daveqnet**
Closes #<issue>

### Code Changes

* [x] Bumped python version in main Dockerfile
* [x] Bumped python version in docs Dockerfile
* [x] Bumped python version in GitHub Actions workflow files

### Steps to Confirm

* [ ] Run `python --version` on fides app image

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Comment by daveqnet** [comment]
Hi @ThomasLaPiana, I just bumped these so that our Docker images based on Debian would also be bumped to latest, but let me know if there are some application impacts I haven't considered.

**Review by ThomasLaPiana — APPROVED** [review]
Thanks for this!

**Comment by ThomasLaPiana** [comment]
@daveqnet LGTM! Any chance you could tackle this on `plus` too? 😁

**Comment by daveqnet** [comment]
> @daveqnet LGTM! Any chance you could tackle this on `plus` too? 😁

Done! 🙂 

https://github.com/ethyca/fidesplus/pull/785

**Pull request merged**
