### PR TITLE
Add a `demo` command

### LINKED ISSUE #1115: Add a `fides deploy` command for users to run an example local environment for demoing or testing
### Is your feature request related to a specific problem?

Currently if a user wants to run fides via the docker-compose file, the only choice they have is to clone the repo and run it that way. This is not a common way for end-users to interact with a tool (repos are usually for development, not for deployment of any kind) and feels like it increases the barrier to entry.

### Describe the solution you'd like

Include docker-compose files as part of the `pip` package and add a CLI command to spin it up. We could also include a subset of the test data scripts (see #1291) to fully configure a data map and privacy request automation.

If we could make it as easy as `pip install ethyca-fides` and `fides deploy` (in the same vein as `fides webserver` and `fides worker`) we could really simplify the act of deploying an instance of `fides` for local or simpler use-cases!

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1115 

### Code Changes

* [x] add a `deploy` command
* [ ] add a bespoke docker-compose file that spins up the application based on the version of the CLI
* [x] teardown the application after it runs
* [ ] add the compose file to the MANIFEST

### Steps to Confirm

* [ ] `fides deploy` spins up a working application!
* [ ] `nox -s test_env` still works

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@NevilleS what're your thoughts on allowing the user to force a version they want to deploy? i.e. they could force dev, latest, etc. (it would need to match the docker image tag) since the command will not rely on the local files/version at all

**Comment by NevilleS** [comment]
That'd make sense to allow some options, but I would say it'd really just be a nice-to-have. By default, I think it should always attempt to use the version that matches the version you've `pip install`-ed so that you can use the CLI with it and have a good version match.

**Comment by ThomasLaPiana** [comment]
I mistakenly thought I would need to package all of the files with the application, but since it really only needs the compose file and everything else is already baked into the container, this gets much easier! Just running a string of docker commands

**Comment by ThomasLaPiana** [comment]
I went down the wrong path and things got super messy, closing in favor of #1508

**Pull request closed without merging**
