### PR TITLE
access and erasure request test

### LINKED ISSUE #1297: Aircall

### LINKED ISSUE #2339: Sparkpost Elite

### PR DESCRIPTION
**Pull request by tmuralikrishnan**
Closes #2339 

### Code Changes
NEW SaaS Connector Sparkpost for access and erasure

### Steps to Confirm
* [x] Add/configure the Sparkpost connector in UI
* [ ] Verify Sparkpost config and icon UI looks good 
* [x] Add receipient data using Sparkpost Api
* [x] Create an Access DSR with the new Sparkpost customer email
* [x] Verify email sent by fides with customer data is correct 
* [x] Create an Delete DSR with the new Sparkpost customer email
* [ ] Verify the customer data is now deleted in Sparkpost

### Pre-Merge Checklist
* [ ] All CI Pipelines Succeeded
* [ ] Update `CHANGELOG.md`

### SaaS Connector Checklist 
* [x] [Spec doc link](https://ethyca.atlassian.net/wiki/spaces/EN/pages/2606006281/Sparkpost+Connector+Specification)
* [x] Vault Creds
* [x] Postman Collection
* [x] SaaS Config And Dataset 
* [x] Access and Erasure Test Passing 
* [ ] Icon

### CODE REVIEW

**Comment by tmuralikrishnan** [comment]
image

**Comment by tmuralikrishnan** [comment]
image

**Comment by tmuralikrishnan** [comment]
image

**Comment by galvana** [comment]
Duplicated by https://github.com/ethyca/fides/pull/3076

**Pull request closed without merging**
