### PR TITLE
[Draft] Sailthru Consent Connector

### PR DESCRIPTION
**Pull request by pattisdr**
Closes https://github.com/ethyca/fidesplus/issues/518

❗ ROUGH DRAFT - UNTESTED

### Code Changes

* [ ] _list your code changes here_

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

First commit - add an initial rough draft of the sailthru consent connector - untested and subject to change. (Credentials needed)

Adds a sailthru authentication override to support https://getstarted.sailthru.com/developers/api-basics/technical/#Authentication_Requests

### CODE REVIEW

**Comment by saiatethyca** [comment]
Based on the docs, I thought this is what we could do for Sailthru.


**On Opt-out**
- Optout_email : basic
- Sms_marketing_status : opt-out
- Sms_transactional_status : opt-out
- Cookies : set to empty


**On Opt-in**
Optout_email : none
Sms_marketing_status : opt-in
Sms_transactional_status : opt-in
Cookies : no action

**Comment by pattisdr** [comment]
Hey @saiatethyca thanks for the feedback here.  `sms_marketing_status` and `optout_email` line up. I'll look into adding `cookies`.  

Are you sure about `sms_transactional_status`?  `transactional` communications seem different than `marketing` communcations.  https://getstarted.sailthru.com/messaging/triggered-messages/transactional-overview/ Just double-checking here.

**Comment by saiatethyca** [comment]
Thanks, Dawn for the response! 
I agree transaction seems aggressive. I'll see if I can get the client's response to this question.

**Comment by pattisdr** [comment]
In the API docs it looks like if you're adding cookies, it's something like this, but I can't find anywhere that an empty dict `{}` removes the cookies?

```
{
    "id":"example@example.com",
    "cookies":
        {
            "sailthru_content":"U9JEVqLefidFAAAA"
        }
}
```

**Comment by pattisdr** [comment]
Closing - this PR is pretty far out of date.  If we get creds for sailthru we can cherry-pick the relevant commit from this branch and continue from there.

**Pull request closed without merging**
