### PR TITLE
Restrict user management capabilities when using the viewer role

### PR DESCRIPTION
**Pull request by allisonking**
~~relies on a fidesui change. need https://github.com/ethyca/fidesui/pull/46 to go in first, then update the import here, before merging~~

Closes https://github.com/ethyca/fidesplus/issues/700

### Code Changes

* [x] Fix bug in password validation which was not allowing users to edit their names (save button wouldn't be enabled)
* [x] Disable permissions tab for viewers
* [x] Restrict the user management row so you can only click into your own profile if you are a viewer. The menu options do not show up either
* [x] Redirect a viewer who is trying to sneakily navigate directly to a user profile
* [x] Cypress tests

### Steps to Confirm

* [ ] Create a user with the `viewer` role
* [ ] Go to the user-management page and click around. You should be able to click into your own profile, but not anyone else's. You also can't click into your permissions tab

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [x] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Comment by allisonking** [comment]
It appears the backend does not allow editing a user's name if they don't have the USER UPDATE permission (even if it's their own user)

The docstring here is not quite right

https://github.com/ethyca/fides/blob/aking/fidesplus-700/restrict-viewer-user-management/src/fides/api/ops/api/v1/endpoints/user_endpoints.py/#L81-L105

**Comment by eastandwestwind** [comment]
@allisonking I'm testing this out locally, and as a `Viewer`, I'm unable to view the user management nav item. Is this expected?

Screenshot 2023-03-29 at 6 32 00 PM

**Comment by eastandwestwind** [comment]
I'm unsure if this was introduced here or has always been an issue, but attempting to update password where the `old password` field is incorrect leads to no err message in the UI telling the user about this error. There is instead a console err:

Screenshot 2023-03-29 at 6 47 15 PM


Otherwise, I've tested the happy path here as a viewer, and everything else looks and functions great!

**Comment by allisonking** [comment]
Thanks @eastandwestwind ! Looks like that's a bug independent of this PR, so I'll log an issue for it and keep this PR trucking along 🚚  

issue here: https://github.com/ethyca/fides/issues/2942

**Pull request merged**
