### PR TITLE
Merge api.ctl into api

### LINKED ISSUE #3091: Fully refactor and integrate `ctl`/`ops` code paths
### Is your feature request related to a specific problem?

The distinction between the different code paths is no longer necessary and enough time has passed that full integration makes sense. The spread out nature of the application makes it harder to navigate and inherently grasp

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #3091 

### Code Changes

* [x] de-nest everything
* [x] combine `utils` and `util` dirs
* [ ] ~~merge `session.py` and `ctl_session.py`~~ (this is taken care of in #3092)
* [x] add another `precheck` CI job that attempts to start the application and prints out healthcheck logs for debugging

### Steps to Confirm

* [ ] N/A

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### Description Of Changes

Final major code re-org PR to `tear down your walls` between previous `ops` and `ctl` code 🙂 

There are still some small idiosyncrasies here and there, but those can get ironed out as needed, and there is a final major follow-up #3092 to unify how sessions are used

### New Dir Structure

```
fides
- api
  - api
  - cryptography
  - db
  - email_templates
  - graph
  - migrations
  - models
  - oauth
  - schemas
  - service
  - task
  - tasks
  - util
  - worker
- cli
- common
- connectors
- core
- data
```

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
had to refer to this article to save myself...https://medium.com/@hamana.hadrien/so-you-got-a-circular-import-in-python-e9142fe10591

**Comment by ThomasLaPiana** [comment]
looks like the final issues here are with `mypy` 🤔 and with the server spinning up

I'm able to spin it up locally though

**Comment by ThomasLaPiana** [comment]
This is quite weird: https://github.com/ethyca/fides/actions/runs/5262756668/jobs/9512378585?pr=3498#step:7:324

The migrations are failing somehow but not locally, even if I do a `nox -s teardown -- volumes` locally I can't reproduce

**Review by SteveDMurphy — APPROVED** [review]
Build looking good and tests are passing for me, tear 'em down! 🏰

**Comment by ThomasLaPiana** [comment]
coverage upload failed, not important

merging!

**Pull request merged**
