### PR TITLE
Add structlog to replace loguru

### LINKED ISSUE #3724: Adopt `structlog` as a replacement for `loguru`
https://www.structlog.org/en/stable/getting-started.html#installation

Although `loguru` is generally a good logging solution, `structlog` has additional functionality that can help us check some other boxes, such as dynamic switching between normal logs and JSON logs

### LINKED ISSUE #3725: Enable serializing logs as JSON

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #3724
Closes #3725 

### Description Of Changes

Replacing `loguru` with `structlog` to enable more advanced logging features and improvements that we want to make in the near-future. They behave very similarly so other than mass import changes there shouldn't be much else that needs to get changed here

The Finalized format will be the following:

Dev Mode:
* Human-readable logging format (non JSON)
* Colorized
* Include file/function/line number in the log

Prod Mode:
* JSON formatting

### Code Changes

* [x] add `structlog` as a requirement
* [x] update imports
* [x] remove `loguru` as a requirement
* [ ] update failing tests (some larger rewrites are required here, but should end up in better tests)
* [ ] update the logging format

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
#### Dev Mode

image

#### Prod (Not Dev Mode)

image

**Comment by ThomasLaPiana** [comment]
@RobertKeyser @seanpreston curious to get your thoughts here on including things like the file/function/line number in the logs

This should technically make things _much_ easier to debug, but I also don't know if it crosses the line of "leaking implementation details". It is trivial to remove so wanted some second opinions

**Comment by RobertKeyser** [comment]
> @RobertKeyser @seanpreston curious to get your thoughts here on including things like the file/function/line number in the logs
> 
> This should technically make things _much_ easier to debug, but I also don't know if it crosses the line of "leaking implementation details". It is trivial to remove so wanted some second opinions

I'm not worried about leaking implementation details in open source Fides; however, that might have a very minor risk for Fidesplus. However, I think that it might add extra noise to the logs with only minor value, so I think we can go without including the filename/line number.

**Comment by ThomasLaPiana** [comment]
Given the extreme complexity of untangling `loguru` in favor of `structlog`, I'm going to close this PR and instead opt for getting the functionality we want working in `loguru`, which should be possible

**Pull request closed without merging**
