### PR TITLE
Get all fidesctl code passing Xenon

### LINKED ISSUE #442: Get `annotate_dataset.py` and `cli/__init__.py` to pass the Xenon checks
### Is your feature request related to a specific problem?

We let these slide, but we should get these in shape and make sure they pass the Xenon checks

### Describe the solution you'd like

removing the exception and making sure these pass the complexity check

### Describe alternatives you've considered, if any

Leaving them as is, _complicated_

### Additional context

n/a

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #442 

### Code Changes

* [x] de-complexify `annotate_dataset.py`
* [x] de-complexify `__init__.py`

### Steps to Confirm

* [ ] `fidesctl annotate dataset demo_resources/demo_dataset.py`

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Issue Requirements are Met

### Description Of Changes

Added new helpers where necessary, to de-complexify `annotate_dataset`.

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@PSalant726 you're a hero

**Comment by ThomasLaPiana** [comment]
@PSalant726 I made a small change but feel free to revert, just wanted to let the user know if the command finished successfully, whether it does something or not (in cases where everything is already annotated for instance)

**Comment by ThomasLaPiana** [comment]
@PSalant726 FYI i can't approve a PR i opened 😢

**Review by PSalant726 — APPROVED** [review]
This feels weird to do, but 🤷‍♂️

**Pull request merged**
