### PR TITLE
Fix mypy errors

### LINKED ISSUE #1148: mypy errors when running
### Bug Description

Note: this is unrelated to #1147 and is a separate issue.

When running mypy I get an error.

```console
src/fides/ctl/core/config/__init__.py: error: Source file found twice under different module names: "src.fides.ctl.core.config" and
"fides.ctl.core.config"
Found 1 error in 1 file (errors prevented further checking)
```

The reason for this error is there is an `__init__.py` in the `src` directory. This makes `src` a python module, and because of this the correct import path for internal modules would be `from src.fides... import...` instead of `from fides... import ...`. 

Further compounding this issue, there is a global `ignore_missing_imports = true` setting for mypy. With the `__init__.py` file in the `src` directory mypy considers every import of fides modules in every file missing imports. Resolving the extra `__init__.py` file issue allows mypy to correctly look at the files and results in several hundred legitimate errors that are currently being missed.

#### Steps to Reproduce

1. run either `mypy .` or `mypy src`

### Expected behavior

mypy should not error when running and should not ignore errors unless explicitly set to do so.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by sanders41**
Closes #1148

### Code Changes

* [x] Removed `__init__.py` from the `src` dir
* [x] Removed the global `ignore_missing_imports = true` and moved needed ignores to the override section
* [x] Fixed mypy errors

### Steps to Confirm

* [ ] Run mypy
* [ ] Run test suite

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Comment by sanders41** [comment]
@ThomasLaPiana are the Fides-Checks expected to fail right now? I didn't make any database changes so I'm wondering if this expected or if something broke.

**Comment by ThomasLaPiana** [comment]
@sanders41 they shouldn't be failing, it looks like someone probably changed the name of the dataset file? I just had them passing in the last PR I merged

**Comment by wiseaidev** [comment]
>  Removed __init__.py from the src dir

Hey guys, just a side note here. Since the `src` folder contains only the package `fides` folder, I suggest moving the `fides` folder outside the `src` folder, and delete that folder. This way the project structure becomes:

<details>
<summary><code>tree -L 2</code></summary> 

```sh
├── CHANGELOG.md
├── clients
│   ├── admin-ui
│   ├── ctl
│   └── ops
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── data
│   ├── config
│   ├── dataset
│   └── saas
├── demo_resources
│   ├── demo_dataset.yml
│   ├── demo_extended_taxonomy.yml
│   ├── demo_organization.yml
│   ├── demo_policy.yml
│   ├── demo_registry.yml
│   └── demo_system.yml
├── dist
│   ├── ethyca_fides-1.8.5.post0.dev632-py3-none-any.whl
│   └── ethyca_fides-1.8.5.post0.dev632.tar.gz
├── docker
│   ├── docker-compose.integration-mariadb.yml
│   ├── docker-compose.integration-mongodb.yml
│   ├── docker-compose.integration-mssql.yml
│   ├── docker-compose.integration-mysql.yml
│   ├── docker-compose.integration-postgres.yml
│   ├── docker-compose.integration-timescale.yml
│   └── sample_data
├── docker-compose.integration-tests.yml
├── docker-compose.yml
├── Dockerfile
├── docs
│   ├── fides
│   ├── fidesops
│   └── README.md
├── fides
│   ├── api
│   ├── cli
│   ├── ctl
│   ├── __init__.py
│   ├── py.typed
│   └── templates
├── LICENSE
├── noxfile.py
├── noxfiles
│   ├── ci_nox.py
│   ├── constants_nox.py
│   ├── dev_nox.py
│   ├── docker_nox.py
│   ├── docs_nox.py
│   ├── run_infrastructure.py
│   └── utils_nox.py
├── pyproject.toml
├── README.md
├── scripts
│   ├── create_test_data.py
│   ├── generate_docs.py
│   ├── mssql_discover.py
│   └── quickstart.py
└── tests
    ├── ctl
    ├── __init__.py
    └── ops
```

</details>

This will also introduce change instances like `src/fides/...` to `fides/...` in the codebase.

**Comment by sanders41** [comment]
There is a chance one of the updates I made to fix a mypy error is causing it also. If so I know which one it would be so I'll look into that.

**Comment by sanders41** [comment]
It was related to a mypy error fix. I went about fixing it in another way and the test is passing now.

**Comment by earmenda** [comment]
nice!

**Comment by sanders41** [comment]
Closing in favor of #1270 for a cleaner change after merging main.

**Pull request closed without merging**
