### PR TITLE
Attentive fix

### PR DESCRIPTION
**Pull request by Vagoasdf**
### Description Of Changes

Currently we have the Attentive email integration as a high level connection type category, and that was causing conflict with lower level connection types, such as the new SaaS Attentive configuration. Since we are transitioning into using SaaS we've updated the reference to attentive_email, in order to avoid name collisions

 Ideally, the Attentive Email integration should be a generic email integration. That should be the next step on the transition

***Note: We Should check our strategy of communication with our clients before updating this, to avoid any breakage***

### Code Changes

* [x] Updated connectionType and connectionConfig attentive references
* [x] Migration for connectionType Attentive

### Steps to Confirm

* [ ] Check that the Attentive Email Integration Works by creating a system for Attentive Email Integration
* [ ] Check that the Attentive Saas Integration Works by creating a system for Attentive Saas Integration. See 1Password for the API KEY

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Issue Requirements are Met
* [x] Update `CHANGELOG.md`
* If there are any database migrations:
  * [x] Ensure that your downrev is up to date with the latest revision on `main`
  * [x] Ensure that your `downgrade()` migration is correct and works
    * [ ] If a downgrade migration is not possible for this change, please call this out in the PR description!

### CODE REVIEW

**Review by galvana — CHANGES_REQUESTED** [review]
It looks like this change has some unwanted change (74 files changed 😬). Can you try fixing or recreating the feature branch to only include the relevant changes?

**Comment by Vagoasdf** [comment]
Looks like something happened with git and it decided to include everything on the main branch that was changed on the previous weeks. Rebased and cleaned it up, it should be ok now

**Review by galvana — APPROVED** [review]
The change looks good! I tested it locally and the upgrade/downgrade worked as expected. I just updated the down revision to be up to date with main and made some small formatting/label changes in the attentive_config.yml but the rest looks solid

**Review by galvana — CHANGES_REQUESTED** [review]
Redacting my approval, it looks like we have some failing tests. Let's fix those before we can merge this in

**Review by galvana — APPROVED** [review]
Thanks for fixing the tests, this looks good to me!

**Pull request merged**
