### PR TITLE
Merge Ops/Ctl docs

### LINKED ISSUE #1008: Update docs on the `unified-fides` branch to merge fidesctl & fidesops
### Docs Update Description

 Right now the docs exist side-by-side, but they need to be properly integrated

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1008 

### Code Changes

* [x] Move files into the `fides` docs dir
* [x] Add navigation for all of the ops pages

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@conceptualshark as more docs updates happen in the respective repos there might be more to merge in the future. After this big reorg gets merged though I should be able to handle the smaller future updates :)

**Comment by conceptualshark** [comment]
😬 Looks scary, but mostly just moving the file structure around to work well with the mkdocs tabs. I think this setup can be temporary depending on what we decide to do with the docs in the near-future, but it should work well to pull everything together for now. 

This doesn't yet include updating the docs so they flow together better, nor removing too many files that are likely doubled-up or redundant now. I can do that on this branch if it's easiest, but didn't want merging this in to fall too far behind.

**Comment by ThomasLaPiana** [comment]
@conceptualshark feel free to do most if not all of the docs merging on this branch, I expect this PR to get us 90% of the way there with docs for unified-fides, with maybe one small follow-up PR after this to merge in any additional changes

**Comment by conceptualshark** [comment]
@ThomasLaPiana I think this stage of the docs is at a good place - I'd like to open another branch that'll just contain the actual docs edits (vs merge).

**Comment by ThomasLaPiana** [comment]
> @ThomasLaPiana I think this stage of the docs is at a good place - I'd like to open another branch that'll just contain the actual docs edits (vs merge).

@conceptualshark Sounds good! I'll take a quick look, merge, and we can pop open another one :)

**Comment by ThomasLaPiana** [comment]
making sure the docs build works after the merge from unified-fides and then merging

**Pull request merged**
