### PR TITLE
Checking Check All Routes

### LINKED ISSUE #2491: browser refresh results in item not find
### Bug Description

_A description of what the bug is._

1. Pull down the lates fides deploy 2.6.0
2. Run deploy up
3. Log in and navigate to any page other than the home page.
4. Click refresh 

### Expected behavior

page should refresh however it errors out with a item not found. it should be noted that this doesn't happen when running test_env

Screen Shot 2023-02-02 at 5 33 12 PM
Screen Shot 2023-02-02 at 5 33 26 PM

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #2491

### Code Changes

* [ ] Add logging where trying to align production build of routes

### Steps to Confirm

* [ ] _list any manual steps for reviewers to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

This appears to only happen when using a production build of the front end, potentially due to the files being compiled in a different path than expected. Originally in `2.5.1`

### CODE REVIEW

**Comment by SteveDMurphy** [comment]
Some example paths:

```
/usr/local/lib/python3.10/site-packages/fides/ui-build/static/admin
fides/src/fides/ui-build/static/admin
src/fides/src/fides/ui-build/static/admin
.venv/lib/python3.10/site-packages/fides/ui-build/static/admin
```

We may need to look at handling an infinite number of preceding path combinations and look at something like `fides/ui-build/static/admin`

**Comment by SteveDMurphy** [comment]
Took a few minutes to give this a little bit of a fresh look with what was discussed by @chriscalhoun1974, @sanders41, @Roger-Ethyca, and @seanpreston on the call tonight - it can definitely be improved with some decent coffee and some sleep but I think it might be a good start towards what we discussed! I was able to validate everything working as planned using `nox -s "fides_env(test)"`

**Comment by sanders41** [comment]
I was going to have another look also, but got unexpected results. I ran `nox -s "fides_env(test)"`, went to a page with a route after the `/` running on 8080, refreshed and got no error. I thought it was weird because I didn't think we had it fixed so I tried on main, again no error.

I do still get errors when using `1.6.0` from docker with `docker pull ethyca/fides:2.6.0` and `pip install ethyca-fides`, but can no longer reproduce it running from the repo. I verified there were no new commits on main from when we were able to reproduce it earlier, and also used incognito mode to rule out cache.

**Comment by sanders41** [comment]
I did some further testing by connecting to the 1.6.0 docker container pulled from pypi and modifying files in the container with the changes here. I found the pages are loading with this change in place. I am getting a 500 error `2023-02-03 03:50:41.683 [WARNING]: Error sending analytics event: The fideslog API responded with an error: 500 Internal Server Error`, but this seems unrelated and maybe the logging server is down?

I was initially concerned this would only work when using our docker image and not when building a custom docker image or pip installing fides. To test this idea I deleted the `src/fides/ui-build` directory, leaving the `ui-build` in the `/usr/local` package directory to mimic a `pip install ethyca-fides`. Doing this the pages still loaded successfully so it seems as though this is working in all situations.

**Comment by SteveDMurphy** [comment]
I'll try and look at the fideslog stuff in a bit. Great catch! Even on failure we shouldn't surface anything if we can help it so am almost hoping it's something to do with the change...

**Comment by sanders41** [comment]
Just to clarify a bit. the 500 error shows in the server log, but pages on the front end still loaded fine without error.

**Comment by SteveDMurphy** [comment]
Ah cool, thank you!

**Comment by chriscalhoun1974** [comment]
Executed `nox -s dev` on this branch. Admin UI running on `http://localhost:3000` works as expected when performing a page refresh via F5 on the top and side level navigation routes.

**Comment by chriscalhoun1974** [comment]
Just tested with `nox -s "fides_env(dev)"` and `nox -s "fides_env(test)"` commands. Page refresh is working as expected using `http://localhost:3000`.

**Comment by SteveDMurphy** [comment]
Closing in favor of #2500

**Pull request closed without merging**
