### PR TITLE
Update sample app with new /landing page

### PR DESCRIPTION
**Pull request by NevilleS**
### Code Changes

* [X] Integrate new landing page
* [X] Automatically launch during `fides deploy up`

### Steps to Confirm

* [x] Build the sample site with `nox -s "build(sample)"` 
* [x] Test using `fides deploy up` locally

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [x] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [x] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

Final finishing touches!

### CODE REVIEW

**Review by NevilleS — COMMENTED** [review]
Tested this out- works like a charm.

**Comment by sanders41** [comment]
I ran `fides deploy up` and everything says it was successful, but it opens to a 404

Screen Shot 2022-11-01 at 6 44 33 PM

**Comment by sanders41** [comment]
I'm still getting the 404 after `nox -s "build(sample)"`

**Comment by NevilleS** [comment]
OK, thanks for trying that out. The /landing assets are definitely there, so I'm a little suspicious as to why that is happening for you... I'm leaning towards getting this on `main` now and cutting another pre-release candidate which will publish to DockerHub.

**Pull request merged**
