### PR TITLE
Admin UI - User Deletion Modal - Only Require One Layer of Confirmation

### PR DESCRIPTION
**Pull request by RobertKeyser**
Closes #<issue>

### Description Of Changes

Today in the Admin UI, we require a user to enter the name of a user to delete twice. While this does indeed confirm that the correct user is about to be deleted, confirming it twice is a bit overkill. Instead, this PR changes the modal to only require the deleting user to enter the target's username once. Additionally, it includes a `<Text>` element with the user's username.

New:
image

Old:
image

Adding the user's name to the deletion modal helps to make sure that you have the right user if you're on the full list of users.

### Code Changes

* [ ] remove one of the username confirmation text fields
* [ ] add a text element with the user's name

### Steps to Confirm

* [ ] create user
* [ ] delete user, there should only be one field for deletion.

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### CODE REVIEW

**Comment by RobertKeyser** [comment]
Are there any Cyprus tests that I'd need to adjust for this? Not sure where to find them (or how to edit them 😸)

**Comment by allisonking** [comment]
It does look like the delete user test is failing 😄 https://github.com/ethyca/fides/actions/runs/6791203976/job/18462232743?pr=4402#step:6:1217

I imagine you have to remove instances where it is looking for that first `username` input https://github.com/ethyca/fides/blob/main/clients/admin-ui/cypress/e2e/user-management.cy.ts#L215

hopefully this [README](https://github.com/ethyca/fides/blob/main/clients/admin-ui/cypress/README.md) can get you going on running the cypress tests locally to see if it passes, but I'm happy to help if you run into anything! sometimes cypress is easy, other times it's super hard 🥲

**Comment by Kelsey-Ethyca** [comment]
This is a nice UX improvement thanks @RobertKeyser! Can I suggest adding some context next to the user name for example "User to be deleted: <user-name>"

**Comment by RobertKeyser** [comment]
New deletion modal: 
image

**Review by Kelsey-Ethyca — APPROVED** [review]
Great ux update and test fix!

UAT passing 
Screenshot 2024-01-31 at 12 33 50 PM

**Pull request merged**
