### PR TITLE
Enable spinning up the Privacy Center from Nox

### LINKED ISSUE #1141: Add a command to spin up the privacy center
### Is your feature request related to a specific problem?

Currently can't spin up the privacy center via nox

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1141 

### Code Changes

* [x] add a build command for the `pc` to nox
* [x] update the `dev` command to accept a posarg for spinning up the pc
* [x] add the `pc` to the compose file

### Steps to Confirm

* [ ] the build command works
* [ ] the posarg spins up the privacy center
* [ ] everything is wired up correctly and the PC is usable

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

This PR gets the privacy center up and running as an optional part of the nox deployment. Accessible at `localhost:3001` via `nox -s dev -- pc`

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
Getting errors here:

When running with `npm run dev`...
```
error - ./pages/_app.tsx:10:0
fides-fides-pc-1  | Module not found: Can't resolve '../config/config.css'
fides-fides-pc-1  |    8 | import "@fontsource/inter/400.css";        
fides-fides-pc-1  |    9 |
fides-fides-pc-1  | > 10 | import "../config/config.css";
fides-fides-pc-1  |   11 |
fides-fides-pc-1  |   12 | import theme from "../theme";
fides-fides-pc-1  |   13 |
```

When running with no command set (using the default entrypoint)
```
fides-fides-pc-1  | ./start.sh: line 4: syntax error: unexpected "fi" (expecting "then")
```

**Comment by ThomasLaPiana** [comment]
@sanders41 can you give me some insight as to how the privacy center is run normally? What env vars it requires, how to boot it up, etc? I looked through the fidesops and plus repos but couldn't find anything

**Comment by sanders41** [comment]
Docs are step 4 [here](https://ethyca.github.io/fidesops/deployment/). For what you are doing all you should need is something like `docker run --rm -p 3000:3000 ethyca/fides-privacy-center:latest`

**Comment by ThomasLaPiana** [comment]
ok, running it like that is working but I'm getting the above errors when trying to run and build locally, I'll make sure all of the files are getting included and there isn't any weird docker ignore stuff happening

**Comment by sanders41** [comment]
That error makes it look like a volume is being mounted, but I don't see one. If there is and I am just missing it make sure that the volume contains both a `config.css` and `config.json` in a `config` directory.

**Comment by sanders41** [comment]
@ThomasLaPiana I got it to start. The main issue was the `command: npm run dev`. There is a script in the container that runs `npm run serve` at startup so it was running dev on top of serve.

The nox command was also starting the ui when pc was passed and both the ui and pc were mapping to port 3000 so I mapped pc to 3001.

**Comment by sanders41** [comment]
That could be the case, it start without error for me. The script it is referencing has the then:

```sh
if [ -d config ]; then
  echo "recompiling with custom configuration..."
  npm run build
fi;

npm run start
```
I did notice I don't have `#!/bin/bash` in there. Would that make it better or worse on Windows? I'm guessing Windows is defaulting to powershell with a .sh file? But I don't think Windows has bash?

**Comment by ThomasLaPiana** [comment]
@sanders41 just as I suspected, I fixed it by changing line endings 🤦

**Comment by ThomasLaPiana** [comment]
@sanders41 is there anything I need to do to wire it up to the database? I'm not sure what the functionality is supposed to be here or how far it can go in its current state

**Comment by sanders41** [comment]
By default it will connect to `http://localhost:8080/api/v1`. There is a section in the `config.json` where that can be changed. So for our development purposes it should work as is without any extra config.

With the dev environment, everything should work as expected out of the box without any modifications.

**Comment by ThomasLaPiana** [comment]
> By default it will connect to `http://localhost:8080/api/v1`. There is a section in the `config.json` where that can be changed. So for our development purposes it should work as is without any extra config.
> 
> With the dev environment, everything should work as expected out of the box without any modifications.

but if the rest of the application is running in docker compose along with it, it would need the special `fides:8080` instead of `localhost` right?

**Comment by sanders41** [comment]
That is actually a good questions. I'm not sure if we have ever run it from docker-compose like this. To customize it what we need to do is copy the `config.json` and `config.css` files from [here](https://github.com/ethyca/fides/tree/unified-fides-2/clients/ops/privacy-center/config). Then [this line](https://github.com/ethyca/fides/blob/990d4a912c1f0b0f9b69bb5575ea338f7eb06dd4/clients/ops/privacy-center/config/config.json#L4) and be configured with the correct url.

Then mount a volume from a directory named `config` to `/app/config` in the container that contains but the `config.json` and `config.css` files.

**Comment by ThomasLaPiana** [comment]
in ctl we're able to configure things via env vars (the URL specifically) so I can try to copy the pattern there

**Comment by sanders41** [comment]
Environment variables are currently not possible in the privacy center, at least as I understand it. But yes this would be nice.

**Comment by ThomasLaPiana** [comment]
ok, so we need a separate dev config altogether for docker it sounds like. I'll dig into this later and try to get it up and running then

**Comment by NevilleS** [comment]
The issues @ThomasLaPiana is debugging now seem to be the exact same problems @azazeldt ran into here: https://github.com/ethyca/fides/issues/1164

So I think this PR will end up fixing both

**Comment by ThomasLaPiana** [comment]
@NevilleS given your other PR, this is good to close now right? huge thanks for the help 🙏

**Pull request closed without merging**
