### PR TITLE
move db-dependent routers up a few levels to reduce circular dependencies

### LINKED ISSUE #3652: the Admin Router is causing circular import issues due to it importing database functions
### Bug Description

`from fides.api.db.database import migrate_db` will throw an error, due to a circular import caused by the `admin.py` defined endpoint

This is annoying but doesn't currently break `fides` directly, however it did require some workarounds in `plus`

### PR DESCRIPTION
**Pull request by adamsachs**
Closes #3652 

### Description Of Changes

our admin (`admin.py`) and health (`health.py`) routers have direct dependencies on the `fides.api.db.database` module, since they require direct interaction with the DB. if these routers are initialized within the `api.api.v1` module, this can easily lead to circular dependency problems on module initialization, because the `api.api.v1` module is itself imported by some classes and submodules of `api.db`. 

see #3652  and this [PR comment](https://github.com/ethyca/fides/pull/3692#issuecomment-1614508211) for context. additionally, this was motivated by @RobertKeyser attempting to import `fides.api.db.database.get_db_health` into a python shell and hitting a circular dependency.

Side note: I considered moving the router definitions themselves (i.e. their code) out of `api.api.v1` and into the higher-level `api` module. but I thought it'd be nice to keep the router definitions next to all the other routers in `api.api.v1`, and just change where the router gets loaded/initialized. i'm definitely open to alternatives, though - what i put here is just a first stab!

### Code Changes

* initialize and load the `HEALTH_ROUTER` and `ADMIN_ROUTER` as part of `api.app_setup` directly, rather than as part of the `api.api.v1.__init__.py` package initializer, as most routers are.

### Steps to Confirm

* [x] server starts (`nox -s dev`, `nox -s "fides_env(test)"`) without import/dependency problems
* [x] `/admin` and `/health` routes work on running server
* [x] automated tests run without import/dependency problems
* [x] `nox -s quickstart` runs to completion without dependency problems
* [x] `fides.api.db.database.get_db_health` can be imported standalone, without dependency problems: 
    * [ ] `nox -s dev --shell`
    * [ ] run `python3` to get a python shell
    * [ ] execute `from fides.api.db.database import get_db_health` successfully

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### CODE REVIEW

**Comment by pattisdr** [comment]
I like the import changes and the choice to keep the router definitions together, this worked well for me in testing. Are there new test failures on this branch?

**Comment by adamsachs** [comment]
> I like the import changes and the choice to keep the router definitions together, this worked well for me in testing. Are there new test failures on this branch?

thanks for taking a look @pattisdr! as far as i can tell, these are test failures that are in `main` (some have been resolved already) - i'm currently hunting down the remaining test issues in `main` separately, since we should get them fixed up in prep for the `2.16.0` release.

so even though the CI failures here are almost certainly unrelated, i'd like to get a clean CI run on this PR just to be sure, given how it's a relatively "core" change. i'll look to merge `main` back into this branch once they're resolved there, and we can let CI run on the PR. no rush on getting this merged as far as i'm concerned.

**Comment by adamsachs** [comment]
@pattisdr nothing changed here since your comment, just rebased off latest `main` to fix up CI. if things still look good, mind giving it a formal 👍 ?

@ThomasLaPiana if you've got a sec, would be good to get your sign off on this too. as we know, this isn't pressing, but since i'd already made the update, figured it's probably worth incorporating?

**Review by pattisdr — APPROVED** [review]

**Comment by ThomasLaPiana** [comment]
@adamsachs I'll take a look at this!! Sorry, I was (too) heads down in the logging work

**Review by ThomasLaPiana — APPROVED** [review]
This is a really elegant solution! Great work here, I don't think there's a better solution than what you implemented here

**Pull request merged**
