### PR TITLE
Remove test_mode

### LINKED ISSUE #1175: [Unified Fides] Populate Application DB instead of Test DB
### Is your feature request related to a specific problem?

Currently, Fides has a "Test mode" setting which populates the test db when True, and the application db when False.  Test mode seems to be True by default.  So when running the application locally, it is the test db that is getting populated.  

Fidesops had "test mode" as False by default. It was not meant to be set as True by anyone, it was just a variable that Pytest set to True to have the Test DB be used. 

For the Fidesops side of things, it is useful to have a separate database from the test database when you're testing privacy requests locally, and depending on some resources to persist there without being created and torn down by the testing harness.

### Describe the solution you'd like

- Populate the normal application database during regular development
- Have Pytest set up and tear down the test database for its own testing 
- Get rid of the "Test Mode" variable, the application doesn't need to set this. Pytest itself should just use the test db.

---

*EDIT ON October 20, 2022 by @ThomasLaPiana*:

After more discussion in the initial PR that is now closed, it was determined that the right way to go forward is the following:

* Remove test mode
* Update ctl database access methods to support injecting/swapping database connections after startup
* Verify that both ops and ctl use the test url when running pytest, and test runs leave the application db untouched

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1175

### Code Changes

* [x] remove `test_mode` and various assertions from everywhere
* [ ] set `pytest` to bring up and tear down a test database entirely for each run using the test database config values

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

Having an explicit test mode added complexity and didn't feel like a great solution. Instead, this PR relies on `dev_mode` where needed to replace `test_mode` and makes the much larger change of updating `pytest` to bring up and tear down its own separate database.

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
migrations aren't working now, getting an error around test mode even though it doesn't get mentioned anywhere, will keep investigating

**Comment by ThomasLaPiana** [comment]
@pattisdr curious what your ideas are for a problem I'm hitting here technically:

In `ctl` we start the webserver, and then run tests against it directly via the API. As far as I can think of, we also have no way to modify the database it is connected to after it starts up. The webserver does its own database setup at startup, so I'm struggling to think of a way to modify the code so that we can inject a new database into the application at runtime without reworking a ton of code (or even if we did rework a ton of code). Do you have any ideas here?

The only thing that I can think of would be to start another instance of the webserver that is pointing at the test database?

**Comment by pattisdr** [comment]
@seanpreston do you know what we did in Fidesops for this? I guess I don't really understand how we fundamentally ran tests over there.

**Comment by ThomasLaPiana** [comment]
When I looked through it, it looks like ops is getting a database session directly, instead of going through the API for most cases

In the cases where it is using the `api_client`, I'm not sure how it wouldn't be modifying the application database itself

**Comment by pattisdr** [comment]
Ah OK, tracing it through

- `api_client` uses FastAPI's [TestClient](https://fastapi.tiangolo.com/tutorial/testing/) and we pass the fidesops application to it
- when an endpoint is hit in the test, `get_db` is injected
- that was eventually calling `get_db_session` in fideslib
- which called `get_db_engine` which checked if [config.is_test_mode](https://github.com/ethyca/fideslib/blob/f6620d4e595a3f9f3697db90a7e6dda6bd4f0765/fideslib/db/session.py#L31)

**Comment by ThomasLaPiana** [comment]
> Ah OK, tracing it through
> 
> * `api_client` uses FastAPI's [TestClient](https://fastapi.tiangolo.com/tutorial/testing/) and we pass the fidesops application to it
> * when an endpoint is hit in the test, `get_db` is injected
> * that was eventually calling `get_db_session` in fideslib
> * which called `get_db_engine` which checked if [config.is_test_mode](https://github.com/ethyca/fideslib/blob/f6620d4e595a3f9f3697db90a7e6dda6bd4f0765/fideslib/db/session.py#L31)

Thanks for tracing it!

Ah I see, so the application itself was aware of test mode...

I guess we have a few options here then:
1. Get rid of test mode as planned, but lose the ability to run tests separately
2. Keep test_mode and update ctl to follow the ops solution. Ctl doesn't use dependency injection though so a (semi) significant rewrite would be needed
3. Since the tests are destructive as-is, we can remove test mode/the concept of a test database altogether and make sure that tests don't run unless `dev_mode` is active.

Do you see any other potential solutions here? Are you leaning towards any in particular?

I don't see any way to really satisfy the original ticket, since it seems like we get to either drop test mode _or_ have separate application and test databases, but maybe I'm not thinking of a clever enough solution

**Comment by pattisdr** [comment]
My main motivation was having a separate application and test database! Getting rid of test mode I thought was just a means to that end, to help unify the ctl and ops pieces, but that doesn't seem to be true.

The current setup is making it difficult to develop ops-related code.  When I'm switching between writing tests and running things locally, I keep finding the database getting wiped because they're sharing the same location.  I think this is a deterrent to running the app locally when we should be doing this more not less.  

So when you lay out those options, I have a strong preference for `#2`

**Comment by ThomasLaPiana** [comment]
> > The current setup is making it difficult to develop ops-related code. When I'm switching between writing tests and running things locally, I keep finding the database getting wiped because they're sharing the same location. I think this is a deterrent to running the app locally when we should be doing this more not less.
> 
> This is the reason we had the tests hit a separate DB to the running application's — if you want to run tests and develop at the same time it's often good for productivity so we should support it.
> 
> > Ctl doesn't use dependency injection though so a (semi) significant refactor would be needed
> 
> @ThomasLaPiana — I'd be interested to see if there's a way we can dynamically change the DB connection URL based on a config var? At it's heart that's all the ops solution does.

Where there's a will there's a way! But I'd have to spend some time thinking about it, and probably look more at the ops solution to get some ideas. I just don't have the bandwidth for this right now, but I agree it's something we should do in the near-term to keep everyone productive. I also welcome anyone who wants to/has ideas to take a pass at it

**Comment by ThomasLaPiana** [comment]
i'm going to update the issue this is related to and then close this PR, since the strategy will be totally different

**Pull request closed without merging**
