### PR TITLE
Guide for Exporting a Data Map / RoPA

### LINKED ISSUE #437: Add a guide for exporting a fully populated data map
### Docs Update Description

With all of the new attribution added to complete an Article 30 compliant RoPA (Record of Processing Activities) a user guide would go a long way to explaining how to reach the finish line.

This should ideally do something like the following:

1. Start with a basic/minimal taxonomy (i.e. `demo_resources`) or alternatively, start from scratch.
2. Work through populating or extending each of the required resources or taxonomy elements.
3. End with exporting a fully populated and article 30 compliant RoPA

### Additional context

Documenting this process in one place with links out to each resource/taxonomy type will provide added value to users that really want to know how to reach this point without searching through multiple layers of documentation.

This will also provide the added value of clearly articulating the level of complexity at this point in time into exporting a RoPA from fides resources

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #437 

### Code Changes

* [x] Add a user guide to our docs for exporting a data map / RoPA
* [x] Fix a typo in the default taxonomy for `Customer`
* [x] ~Potentially record a video of this process as well for users that would benefit?~ Deferred

### Steps to Confirm

* [x] Review, edit, critiquing by both Cole and Kelly

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Documentation Updated
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created

### Description Of Changes

~This is still in a very rough draft state, wanted to get some ideas on paper for how this story can be told.~

Feeling a bit better about the content coverage at least, if there is time I think walking through this guide would be really helpful. I also feel like there could be a few different ways to tell this story but I think this was a good way to showcase the new properties without having to cover everything from the core product in detail again.

Once everyone is happy with the format and flow of the guide, I think having a video explainer as well could go a long ways. I need to re-record something short on Loom anyways so was going to do a longer version for us to either embed in the docs or post externally. Thanks for the help!

### CODE REVIEW

**Comment by conceptualshark** [comment]
What would be easiest for you to have this reviewed? If most of the information is here, I'd love to commit organization/edits direct to this branch when ready.

**Comment by SteveDMurphy** [comment]
> What would be easiest for you to have this reviewed? If most of the information is here, I'd love to commit organization/edits direct to this branch when ready.

Thanks @conceptualshark !! I'm just about to update the PR description with some further details, but I think this should be ready for a review now. I'm not sure if it makes sense to try and work through the guide itself or if that was something @iamkelllly was interested in doing. Feel free to push any changes you see fit, thanks!! 🙌🏽

**Review by ThomasLaPiana — APPROVED** [review]
LGTM!

**Comment by SteveDMurphy** [comment]
Thank you for the updates here @ThomasLaPiana !! 🔥 🔥

**Review by conceptualshark — APPROVED** [review]

**Comment by SteveDMurphy** [comment]
Thank you for the lovely updates @conceptualshark !! 💥

**Pull request merged**
