### PR TITLE
Remove the dependabot auto PR workflow

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes <issue>

### Code Changes

* [x] remove the `dependabot.yaml` workflow file

### Steps to Confirm

* [ ] it doesn't exist anymore

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

More noisy than anticipated due to some packages being updated very often.
@PSalant726 i yield

### CODE REVIEW

**Comment by sanders41** [comment]
@ThomasLaPiana No objections if you want to remove it, but just to point out if you want it, you can set it to run on intervals like one a week, once a month, etc. Would make it less noisy.

**Review by sanders41 — APPROVED** [review]
lgtm

**Comment by ThomasLaPiana** [comment]
> @ThomasLaPiana No objections if you want to remove it, but just to point out if you want it, you can set it to run on intervals like one a week, once a month, etc. Would make it less noisy.

I think my strategy going forward would be to open an issue maybe once-per-release or so and bump dependencies there. That way we are still keeping things up-to-date on a regular basis but without 20 open PRs (lots of bot PRs being open feels just as noisy as the stream of messages in slack)

**Comment by ThomasLaPiana** [comment]
@sanders41 thanks for the quick review!

**Pull request merged**
