### PR TITLE
Unnest `ops` API code

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
### Code Changes

* [x] move the `fides.api.ops` dir up one into `fides.api`

### Steps to Confirm

* [x] tests pass

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded (failures are all expected failures)
* [x] Relevant Follow-Up Issues Created ([follow-up plus issue](https://github.com/ethyca/fidesplus/issues/900)]
* [x] Update `CHANGELOG.md`

### Description Of Changes

In preparation for fully integrating ops/ctl code, this small (but with a large diff 😬 ) iteration unnests the ops code into `fides.api`

### CODE REVIEW

**Review by adamsachs — APPROVED** [review]
this looks good, did some smoke testing on my local server too and things generally looked fine.

only question is around the failures with external saas tests - i'm almost positive those are unrelated to the changes, just the fact that there are so many (and with some rather unusual suspects from my experience) give me pause. there also aren't any logs showing the failures/errors - maybe this is normal in CI?

looping in @galvana who's got some more recent experience with the saas tests to make sure things look OK from his POV!

**Comment by ThomasLaPiana** [comment]
> this looks good, did some smoke testing on my local server too and things generally looked fine.
> 
> only question is around the failures with external saas tests - i'm almost positive those are unrelated to the changes, just the fact that there are so many (and with some rather unusual suspects from my experience) gives me pause. there also aren't any logs showing the failures/errors - maybe this is normal in CI?
> 
> looping in @galvana who's got some more recent experience with the saas tests to make sure things look OK from his POV!

That is correct, we don't show those test logs in CI for security reasons. To put it simply, I did a mass search find for any mention of `fides.api.ops`, `fides/api/ops`, and other combinations so I truly don't _think_ this PR would break it but also can't verify due to the logs being obscured.

To avoid continually spending time on merge conflicts, I'd rather ship now and follow up with a smaller PR that might fix any particular bug that slipped through

**Comment by adamsachs** [comment]
> > this looks good, did some smoke testing on my local server too and things generally looked fine.
> > only question is around the failures with external saas tests - i'm almost positive those are unrelated to the changes, just the fact that there are so many (and with some rather unusual suspects from my experience) gives me pause. there also aren't any logs showing the failures/errors - maybe this is normal in CI?
> > looping in @galvana who's got some more recent experience with the saas tests to make sure things look OK from his POV!
> 
> That is correct, we don't show those test logs in CI for security reasons. To put it simply, I did a mass search find for any mention of `fides.api.ops`, `fides/api/ops`, and other combinations so I truly don't _think_ this PR would break it but also can't verify due to the logs being obscured.
> 
> To avoid continually spending time on merge conflicts, I'd rather ship now and follow up with a smaller PR that might fix any particular bug that slipped through

that's good with me! sorry, looks like you've already got some conflicts :/

**Comment by ThomasLaPiana** [comment]
> > > this looks good, did some smoke testing on my local server too and things generally looked fine.
> > > only question is around the failures with external saas tests - i'm almost positive those are unrelated to the changes, just the fact that there are so many (and with some rather unusual suspects from my experience) gives me pause. there also aren't any logs showing the failures/errors - maybe this is normal in CI?
> > > looping in @galvana who's got some more recent experience with the saas tests to make sure things look OK from his POV!
> > 
> > 
> > That is correct, we don't show those test logs in CI for security reasons. To put it simply, I did a mass search find for any mention of `fides.api.ops`, `fides/api/ops`, and other combinations so I truly don't _think_ this PR would break it but also can't verify due to the logs being obscured.
> > To avoid continually spending time on merge conflicts, I'd rather ship now and follow up with a smaller PR that might fix any particular bug that slipped through
> 
> that's good with me! sorry, looks like you've already got some conflicts :/

haha no worries! I knew I wouldn't get away clean this time 😂 after going through the Fides 2.0 merge I think I can handle just about anything in terms of conflicts

**Pull request merged**
