### PR TITLE
Update taxonomy forms

### PR DESCRIPTION
**Pull request by allisonking**
Closes https://github.com/ethyca/fides/issues/998

### Code Changes

* [x] Extends the forms for DataSubjects and DataUses based on the [updated requirements](https://github.com/ethyca/fides/issues/858#issuecomment-1219558924)
  * [x] Adds a new prop `extraFormFields` and renames the original form to `TaxonomyFormBase` so other forms can build off of it
  * [x] Adds more props to the hooks now that there are more unique fields between taxonomy types
    * [x] Does this via typescript generics... this is my first time somewhat successfully using them, so very open to suggestions if I'm doing it weirdly 😅 
* [x] Updates a few of the form inputs to take data-testid the same way as everyone else
* [x] Adds cypress tests

### Steps to Confirm

* [ ] Go to the /taxonomy page and try editing the forms for DataSubjects and DataUses

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
  * https://github.com/ethyca/fides/issues/1001
* [x] Update `CHANGELOG.md`

### Description Of Changes

https://github.com/ethyca/fides/pull/977 was clever about reusing the same component and isolating unique attributes to hooks. This worked well back when the edit form was the same across every taxonomy type. Now that they're no longer the same, we are still able to use the same pattern, but it might make things a little harder to grok, in exchange for cleaner components.

image

image

DataCategory and DataQualifier forms still look the same.

### CODE REVIEW

**Review by ThomasLaPiana — APPROVED** [review]
LGTM! Played around with it and all worked as expected

**Comment by ThomasLaPiana** [comment]
@allisonking this is a random thought and unrelated to this ticket, but I didn't want it to get lost and potentially we could open another issue for it.

The UX here feels a bit weird to me. When I click on an item from the list nothing happens. No feedback at all, instead I have to use the `edit` button to get the item to pop up in the side drawer (I think that's what it's called?) to see more info.

I think my preferred behavior here would be to click on the item in the list, and have it immediately open to the side. There is no need for an `edit` button if it automatically opens, and we could add a red `delete` button next to the `update` button.

Thoughts? The current method felt immediately unintuitive to me

**Comment by allisonking** [comment]
> @allisonking this is a random thought and unrelated to this ticket, but I didn't want it to get lost and potentially we could open another issue for it.
> 
> The UX here feels a bit weird to me. When I click on an item from the list nothing happens. No feedback at all, instead I have to use the `edit` button to get the item to pop up in the side drawer (I think that's what it's called?) to see more info.
> 
> I think my preferred behavior here would be to click on the item in the list, and have it immediately open to the side. There is no need for an `edit` button if it automatically opens, and we could add a red `delete` button next to the `update` button.
> 
> Thoughts? The current method felt immediately unintuitive to me

Yeah I definitely see where you're coming from. I have two concerns with this approach but maybe we can work around them:

1. If users don't click on the item at all, they won't know the edit/delete features are available 
2. The parent fields, when clicked on, open up to reveal their children fields. This feels intuitive to me. If we wanted "edit on click" like you're describing, we'd have two things that happen when clicking on a parent field: opening up the children, and also opening up the side drawer. The children elements would only open up the side drawer as you're describing which works well, but the parents have a bit more going on. It seems like it'd be annoying if you're just trying to open up parents, for the side edit drawer to appear for each of them on each click.

Perhaps @mfbrown can weigh in, or we can ask the design team? Adding a video for easy reference

https://user-images.githubusercontent.com/24641006/185950199-bd0f93f1-09c8-4ca9-bd0a-debf86c045ae.mov

**Comment by allisonking** [comment]
Made a ticket for Thomas' suggestion here: https://github.com/ethyca/fides/issues/1003

Going to merge this in the mean time to keep work flowing

**Pull request merged**
