### PR TITLE
Add a make target to spin up only the database

### LINKED ISSUE #468: Add a Make target that only spins up the db
### Is your feature request related to a specific problem?

It uses a lot of battery to be running lots of docker containers....inconvenient when working in a very portable manner

### Describe the solution you'd like

Add a `make local` command (or something like that) that will run the postgres db inside of a docker container but will then spin up an auto-reloading webserver in the local terminal instead of docker.

### Describe alternatives you've considered, if any

Running a postgres database locally too...but this just seems like too much work/configuration/prone to error

### Additional context

Should do testing here to make sure that running 1 docker container uses significantly less power than 2-3. Can measure the memory/CPU usage/wattage being consumed to make an objective decision.

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #468 

### Code Changes

* [x] add the make target for just the db

### Steps to Confirm

* [x] run `fidesctl` commands with a local install of `fidesctl` that points to a `localhost` db

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Documentation Updated
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created

### Description Of Changes

For the sake of being able to dev when away from a power outlet, this option has been added as an even lower-power way to do some work when needed. It also helps us test `fidesctl webserver` more easily.

### Power testing on my windows machine:

1. Using the dev containers: 10-14 watts
2. `make cli`: 9-12 watts
3. `make api` with the CLI running locally: 9-12
4. `make db` with the webserver and CLI running locally: 4-6

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@PSalant726 i'm seeing this error when running locally:

(base) PS C:\Users\tal10\Documents\Git\fides> fidesctl status
Getting server status...
Server is reachable and the client/server application versions match.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000253304290D0>
Traceback (most recent call last):
  File "C:\Users\tal10\anaconda3\lib\asyncio\proactor_events.py", line 116, in __del__  
    self.close()
  File "C:\Users\tal10\anaconda3\lib\asyncio\proactor_events.py", line 108, in close    
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\tal10\anaconda3\lib\asyncio\base_events.py", line 719, in call_soon    
    self._check_closed()
  File "C:\Users\tal10\anaconda3\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Review by SteveDMurphy — APPROVED** [review]
Looks good!

**Comment by ThomasLaPiana** [comment]
I've confirmed that the CLI works just fine when opting out of analytics

**Comment by ThomasLaPiana** [comment]
going to merge this and then open another issue for that...

**Pull request merged**
