### PR TITLE
2898 alert system manager downgrade to approver

### PR DESCRIPTION
**Pull request by eastandwestwind**
Closes https://github.com/ethyca/fides/issues/2898

### Code Changes

* [ ] Adds confirmation modal when attempting to downgrade user to approver if they are assigned systems.

### Steps to Confirm

* [ ] Assign user as anything other than approver, and assign systems
* [ ] Click save
* [ ] Assign user to approver
* [ ] Click save
* [ ] See confirmation modal
* [ ] Confirm nothing happens if you click `cancel`
* [ ] Confirm user is saved with approver role if you click `yes`

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Review by allisonking — APPROVED** [review]
this lgtm—the UX is a little strange right now while Dawn's PR isn't in yet, so we'll just want to test that everything feels intuitive after that PR goes in as well (or create a branch with both this change and Dawn's change just to test things out)

i.e. right now the systems are retained


https://user-images.githubusercontent.com/24641006/228259169-05d94569-92d0-43ba-9610-7f2f83811a93.mov

I think that should just be because the backend isn't getting rid of them, but there's always the chance the FE is keeping the state somewhere, so we'll want to watch for that.

**Comment by eastandwestwind** [comment]
This err was being thrown when attempting to downgrade a user from viewer to approver (when the user has systems assigned):

Screenshot 2023-03-29 at 8 01 55 PM

Since the removal of systems occurs on the BE, we shouldn't call the PUT ``user/${userId}/system-manager` API endpoint when users are downgraded to approver. I've updated the code accordingly.

**Comment by eastandwestwind** [comment]
> this lgtm—the UX is a little strange right now while Dawn's PR isn't in yet, so we'll just want to test that everything feels intuitive after that PR goes in as well (or create a branch with both this change and Dawn's change just to test things out)
> 
> i.e. right now the systems are retained
> 
> I think that should just be because the backend isn't getting rid of them, but there's always the chance the FE is keeping the state somewhere, so we'll want to watch for that.

I've also confirmed that this issue is now fixed after pulling in latest BE

**Review by allisonking — APPROVED** [review]
good catch! glad it's all working nicely 💥

**Pull request merged**
