### PR TITLE
Upgrade FastAPI to 0.85.1

### LINKED ISSUE #1855: Upgrade FastAPI to at least 0.85.1
### Is your feature request related to a specific problem?

Our current version of FastAPI has a regression that can't support strings in OpenAPI status codes, "1XX", "2XX", "3XX" etc which was fixed in 0.85.1 

https://github.com/tiangolo/fastapi/releases/tag/0.85.1

We're looking into upgrades for fidesops-plus masking work and this upgrade would be beneficial over there.  

### Describe the solution you'd like

_A description of what you want to happen._

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

_Add any other context or screenshots about the feature request here._

### PR DESCRIPTION
**Pull request by pattisdr**
Closes #1855 

### Code Changes

* [ ] Upgrade Fast API to 0.85.1

### Steps to Confirm

* [ ] Bring up application server
* [ ] Make several API requests against ctl and ops endpoints

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

Upgrade Fast API. Fast API 0.79 - 0.85 has a bug that doesn't handle strings in OpenAPI status codes https://github.com/tiangolo/fastapi/pull/5187.

### CODE REVIEW

**Review by sanders41 — APPROVED** [review]
0.88.0 is the latest version. Is there are reason not to update to that version?

**Comment by pattisdr** [comment]
> 0.88.0 is the latest version. Is there are reason not to update to that version?

Hi @sanders41 thanks for reviewing! No real reason other than that I've done a lot of testing of this version and no testing of the latest.

**Comment by pattisdr** [comment]
Seeing ` sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)` after bringing this up-to-date with main, this happened several times - will not be merging until I know what this is.

**Comment by sanders41** [comment]
@pattisdr looks like 0.88.0 is also failing, but for different reasons #1863. The failures with 0.85.1 I'm not sure what is causing this.

I think I understand the failures in 0.88.0 and know how to fix them. The `TestClient` was changed from `requests` to `httpx` so the methods/arguments need to be updated for httpx.

**Comment by pattisdr** [comment]
Closing - we should just update to 0.88.0 in https://github.com/ethyca/fides/pull/1863.

**Pull request closed without merging**
