### PR TITLE
Fix shell command in README quickstart

### LINKED ISSUE #1411: Quickstart `nox -s dev` command in readme not complete
### Bug Description

In the readme there is an instruction to run `nox -s dev` then wait for the prompt. In order to get this prompt the command should be `nox -s dev -- shell`

#### Steps to Reproduce

1. run `nox -s dev`
1. no shell is started

### Expected behavior

Shell should start to match instructions.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by sanders41**
Closes #1411

### Code Changes

* [x] Changed the nox command from `nox -s dev` to `nox -s dev -- shell` in the README quick start. 
* [x] update the banner image
* [x] clean up verbiage

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

Quick README cleanup post-unify

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@sanders41 I think we should clean up _all_ of the README, since Dave found lots of issues in that issue

**Comment by sanders41** [comment]
Yes, I just saw he found some more. I will go through his findings and also look to see if I find any more.

**Comment by sanders41** [comment]
@ThomasLaPiana I made updates to the README from the issues Dave found, and also a couple additional ones I found.

I was able to reproduce the `fides push demo_resources/` error when starting fresh, but interestingly not always. I opened an issue here #1435. I think it's going to be a tough one to track down since I can't consistently get it to error.

For the warning messages I did a global search of the project and couldn't find those log messages so I'm not sure where they are coming from. I opened an issue for this one here #1434.

**Comment by ThomasLaPiana** [comment]
@sanders41 the warning messages for the env vars are actually coming from docker, and Neville fixed them in another PR (https://github.com/ethyca/fides/pull/1457)

I'll play around with this and try to figure out the `push` issue, since it should be checking the webserver's health before trying to run and that's the only intermittent thing I can think of here 🤔

**Comment by sanders41** [comment]
I just had a thought and I haven't had a chance to look into it yet so it may not make sense. Could it be possible that on the first run something gets written somewhere like fides.toml and it works after that? That would explain why it fails on the first run and works after that. It would also explain why it worked for me after clearing the volumes and trying again because clearing the volumes wouldn't clear what was written to the file.

**Comment by ThomasLaPiana** [comment]
@sanders41 it ran just fine for me, which just means it didn't hit the intermittent error I guess

I'm cleaning up some other stuff and will push up another version shortly :)

**Review by ThomasLaPiana — APPROVED** [review]

**Comment by ThomasLaPiana** [comment]
uhhh I don't think these test failures are related but they are weird

**Comment by sanders41** [comment]
They are not related. This failure is happening everywhere now. I tried to track it down, but the test passes when I run it locally.

**Review by conceptualshark — APPROVED** [review]
🙏 Thank you! Great updates!

**Pull request merged**
