### PR TITLE
Add Docker Hub auth to rate-limited CI workflows

### PR DESCRIPTION
**Pull request by daveqnet**
Closes OPS-772

### Description Of Changes

* Add Docker Hub auth to Cypress E2E Tests workflow
* Add Docker Hub auth to Backend Code Checks workflow
* Removes hardcoded Docker username in Publish Docker Images workflow and upgrades action to latest (v3)

### Code Changes

* Adding Docker Hub auth for a premium user will increase the rate limit to 5000/day instead of the 100/6 hours for unauth'd Docker users. 

### Steps to Confirm

* Run currently failing CI jobs for modified workflows and ensure they pass.

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
  * [ ] if there are any new client scopes created as part of the pull request, remember to update public-facing documentation that references our scope registry
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated
* If there are any database migrations:
  * [ ] Ensure that your downrev is up to date with the latest revision on `main`
  * [ ] Ensure that your `downgrade()` migration is correct and works
    * [ ] If a downgrade migration is not possible for this change, please call this out in the PR description!

### CODE REVIEW

**Review by RobertKeyser — APPROVED** [review]
Looks good to me!

**Review by RobertKeyser — APPROVED** [review]
I did notice in other workflows, we define them as environment variables with the following pattern under the env key

```
  DOCKER_USER: ethycaci
  DOCKER_RO_TOKEN: ${{ secrets.DOCKER_RO_TOKEN }}
```

And then use those envs instead of the secrets directly. 

I think this should work, but if it doesn't, we'll go that route. Either way, approved.

**Comment by daveqnet** [comment]
Adding Do Not Merge label. The Backend Code Checks workflow needs to be rethought as the actions step logs into Docker Hub... and then logs out before the next job where auth is needed 🥹 
Screenshot 2024-10-14 at 17 55 32

**Review by RobertKeyser — APPROVED** [review]
Good catch! Looks good to me.

**Comment by daveqnet** [comment]
Thanks Rob! Assuming CI passes, I'll merge this in the morning.

**Pull request merged**
