### PR TITLE
Add missing docs references

### LINKED ISSUE #1186: [Unified Fides] Missing Fidesops Docs in Index
### Bug Description

The combined fides/fidesops mkdocs.yml file is missing references to `manual_webhooks.md` and `connection_types.md`

- `manual_webhooks.md`
- `connection_types.md` 

#### Steps to Reproduce

1. _Do this..._
1. _Then This..._

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #1186

### Code Changes

* [x] Include `manual_webhooks.md` and `connection_types.md` in `mkdocs.yml`
* [x] Include `fidesops_workflow.md` and missing assets
* [x] Update all broken links showing in terminal
* [x] Delete no longer required docs

### Steps to Confirm

* [x] Walked through docs for any other required updates

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  * [x] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [x] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

Looking to do one more pass of items that may be missing links before taking out of draft

### CODE REVIEW

**Comment by pattisdr** [comment]
Please keep `fidesops_workflow.md` we had recently added that over in fidesops, to describe how a privacy request is run! Maybe it needs to be resurfaced in the index if it isn't already.

**Comment by SteveDMurphy** [comment]
Thank you both! Will make the changes and put into review, planning to remove `review_checklist.md` as well

**Comment by SteveDMurphy** [comment]
Normally I don't think we would need/want all of these checks to run for docs changes so am not concerned at this point

**Review by conceptualshark — APPROVED** [review]

**Comment by SteveDMurphy** [comment]
@ThomasLaPiana I think when I was trying to clean this branch up the commit history got a little expanded - ok to squash and merge these in still or want me to just delete and create a new branch ?

**Pull request closed without merging**
