### PR TITLE
Add a test collection workflow pre-step

### LINKED ISSUE #2033: Add a pytest collection CI workflow
### Is your feature request related to a specific problem?

Sometimes a ton of CI jobs run even if there are critical syntax errors

### Describe the solution you'd like

A pre-step that runs `pytest tests/ --collect-only` should run before the backend CI suite and cancel out quickly if it fails

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #2033 

### Code Changes

* [x] add a nox command to collect tests
* [x] add a workflow job that runs the test collection nox session
* [x] make all test-related workflows conditional on the `Collect-Tests` workflow step via the `Build` step

### Steps to Confirm

* [ ] run `nox -s collect_tests` locally (first run will take awhile as it caches the installations)
* [ ] verify the `Collect-Tests` job runs as expected and the output looks correct
* [ ] verify that if the `Collect-Tests` doesn't pass, the pytest jobs don't get run

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [x] Issue Requirements are Met
* [ ] ~~Relevant Follow-Up Issues Created~~
* [x] Update `CHANGELOG.md`

### Description Of Changes

This is meant to be a straightforward PR that will serve to both
1. Transparently show code coverage for the entire test suite on every run (at least when analyzed statically)
2. Fail fast if there are any test collection errors and block the expensive pytest jobs from running

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
the above CI check shows that when the collection passes, everything runs as usual.

I'll now purposefully break the collection to confirm that the tests wont run

**Comment by ThomasLaPiana** [comment]
the above CI run should break and prevent pytests from running

**Review by sanders41 — APPROVED** [review]
LGTM!

This is good like it is, just a question. Would it be worth it to move the collection test to the docker build since that step is what takes longest to run and the pytest steps won't run without build?

**Comment by ThomasLaPiana** [comment]
> LGTM!
> 
> This is good like it is, just a question. Would it be worth it to move the collection test to the docker build since that step is what takes longest to run and the pytest steps won't run without build?

Oh, that makes way more sense! Ok, i'll make `build` rely on `collect-tests`

**Comment by sanders41** [comment]
The skipped and failed tests here look to me to be github network related and not PR related. Restarting to see if that fixes it.

**Review by sanders41 — APPROVED** [review]
The failure again looks unrelated to the PR

**Pull request merged**
