### PR TITLE
fix: update EU based cookiehouse geo strings

### LINKED ISSUE #3762: Cookiehouse EU Geostrings are incorrect
### Bug Description

When using cookie house, the France and Germany do not work. 

#### Steps to Reproduce

1. Open cookie house
2. Click an EU country 

### Expected behavior

1. Banner should pop up

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by nicolas-ethyca**
Closes #3762 

### Description Of Changes

1. Modify Geostrings to match seed 

### Code Changes

* [ ] Modified Strings

### Steps to Confirm

* [ ] Launch Cookiehouse and click on Germany
* [ ] Click on France
* [ ] See banner pop up in both scenarios

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### CODE REVIEW

**Comment by allisonking** [comment]
Thanks for the PR! @pattisdr actually fixed this here: https://github.com/ethyca/fides/pull/3630. the backend is now able to accept a code like `fr_idg` and figure out which experience to use (basically we reworked how region search/filter worked to handle cases like "country groups"). It seems like it's working how you want it here: https://cookiehouse-plus-nightly.fides-staging.ethyca.com/?geolocation=FR-IDG. If that seems right to you, then I think we can close this PR and the original ticket 👍

**Comment by nicolas-ethyca** [comment]
@allisonking I tried it for Paris and it worked, for Frankfurt, the modal was not appearing

**Comment by pattisdr** [comment]
@nicolas-ethyca can you see which region is getting passed to the backend for frankfurt?  It's a `region` query param that will be attached to the GET /privacy-experience call

**Comment by nicolas-ethyca** [comment]
@pattisdr as I was looking at the trace, it rendered lol sorry for the confusion. Idk why it took a few seconds to render switching from Paris (which I did first) but disregard /shrug

image

**Pull request closed without merging**
