### PR TITLE
Add Exception Handling to Generate Route

### LINKED ISSUE #892: Make the generate endpoint return more helpful error messages on failure
### Is your feature request related to a specific problem?

Right now if you try to use the generate endpoint to connect to a database that doesn't exist, there will be an internal server error. Therefore, the frontend can only show "An unexpected error occurred". 

### Describe the solution you'd like

We should do our best to catch common error cases (malformed URL, db unreachable) and return that message instead of internal server error-ing.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Came up as a result of https://github.com/ethyca/fides/pull/889

Can reproduce with

```
curl -X 'POST' \                                              
  'http://localhost:8080/api/v1/generate/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "organization_key": "default_organization",
  "generate": {
    "config": {
      "connection_string": "fake_string"
    },
    "target": "db",
    "type": "datasets"
  }
}'
```
which will give an Internal Server Error

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #892

### Code Changes

* [x] validate all connectors and respond appropriately

### Steps to Confirm

* [x] Bad config returns a 401 now instead of a 500

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [x] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [x] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

Just wanted to get something out quick to see if it starts to look more like what would be expected on the front end.

### CODE REVIEW

**Comment by SteveDMurphy** [comment]
Heyo @ssangervasi ! Wanted to put something together quick in case it helps as a starting point for some of the exception handling we wanted to add. If you have time, could you let me know if this is looking more like what you would want to see? Right now it's just doing some extra validation on the credentials (but I think that may be a separate step in the config as well via the `validate/` endpoint)

**Comment by allisonking** [comment]
Looking good, much better error than before!

Putting in a URL that really isn't a URL

image

A URL that can't be reached (db isn't up)

image

Scanning AWS 

image

**Comment by SteveDMurphy** [comment]
Incorporated updates for the `BigQuery` connector as well, thanks for the early review @allisonking ! I think it makes sense to move ahead with this as is, and then based on what we decide we can either pivot to use the `/validate` endpoint or continue to iterate with this as needed

**Review by ThomasLaPiana — APPROVED** [review]
LGTM! Smart update, much better UX

**Comment by ThomasLaPiana** [comment]
@SteveDMurphy I think this change is great. I think having the `generate` endpoint doing validation in addition to the `validate` endpoint is a smart move. Afterall, people shouldn't need to call a separate endpoint just to get a good error message if `generate` fails

**Pull request merged**
