### PR TITLE
Update pre-commit-config.yaml

### LINKED ISSUE #526: pre-commit does not find files after project restructure
### Bug Description

After the restructuring of the project directories pre-commit no longer finds the files to check. Prior to this update I had a separate issue with the pre-commit config throwing errors. Pre-commit uses caching to speed things up and I think this was not playing well with the use of Docker to run the checks. After one run I would always have to clean the pre-commit cache in order to run again without errors.

Pre-commit is an awesome tool that I would like to use so I am going to open a PR with a proposal for an update to the `pre-commit-config.yaml` that will make it both much faster to run the checks and run without error. It will only take me a couple minutes to put the proposal together so if no one else likes it and would rather close it, it won't be a big loss.

#### Steps to Reproduce

1. Make any change to the code
1. Run `pre-commit run -a`

### Expected behavior

pre-commit should run checks

### Screenshots

Screenshot from 2022-04-27 08-28-25

### Environment

* Version: 1.5.3
* OS: Linux
* Python Version: N/A
* Docker Version: N/A

### Additional context

The current `pre-commit-config.yaml` file is looking for the top level `fidesctl` directory, but this directory no long exists so no files are checked.

### PR DESCRIPTION
**Pull request by sanders41**
Closes #526

### Code Changes

* [x] Updated the `pre-commit-config.yaml` file to run without Docker
* [x] Added `__init__.py` files in the test directories so mypy can work with them porperly
* [x] Added as mypy tests section to setup.cfg to all untyped defs in tests

### Steps to Confirm

* [ ] Run `pre-commit install`
* [ ] Run `pre-commit run -a` and verify all hooks run

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

The core of the changes are I removed the docker check because it is slow to run, and I make the hooks directly on the code outside of docker. The docker build is part of the CI check so it still gets checked, just outside of pre-commit.

There are several updates the hooks are wanting me to make when they run, mostly because they are running on the test directories also which isn't currently done. Before I go through and make any suggested updates I wanted to make sure this change is something that would be wanted.

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@sanders41 I agree that the pre-commits can be slow, I honestly don't use them and just do a `make check-all` before each commit.

The main thinking behind this was to make sure that our local checks are the same as CI, so we don't have to do any "debug via CI" madness, but I also get it isn't great from a dev flow perspective.

I'm thinking that #518 might alleviate some of these issues so its probably worth waiting until that gets shipped to then fix up the pre-commit. How does that solution feel?

Thanks for doing this by the way!

**Comment by PSalant726** [comment]
Just throwing in my $0.02 - we could always nix the third party tool and switch to git-native pre-commit hooks 👀

**Comment by sanders41** [comment]
I'm certainly open to any option. The thing I like about per-commit is is you don't have to think about it, any time you commit it runs so you can't forget. That said if you do forget, CI will still catch things so not the end of the world.

@PSalant726 advantages I see to pre-commit installing the hooks are a couple. First it make sure everyone is using the same hooks with the same settings (including automatically updating the hooks when the config file is updated. Second it makes it really easy, `pre-commit install` vs needing to know how to install them yourself.

**Comment by ThomasLaPiana** [comment]
@sanders41 is this worth revisiting now? I think I can take a swing at it now that the other PRs are closed

**Comment by sanders41** [comment]
I would say yes. I think pre-commit is really nice.

**Comment by ThomasLaPiana** [comment]
closing for now, will revisit in the future though

**Pull request closed without merging**
