### PR TITLE
Added carets to collapsible sections in the overlay modal

### PR DESCRIPTION
**Pull request by guncha**
### Description Of Changes

Cherry-picking the CSS used to implement an animated caret for the notice elements. See https://github.com/ethyca/fidesplus/pull/1374#discussion_r1556149459

Also changed CSS  so that the caret will rotate the _right_ way - counter clockwise on open.

carets

### Code Changes

* [x] CSS change using pseudo-elements

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Update `CHANGELOG.md`

### CODE REVIEW

**Review by gilluminate — APPROVED** [review]
love it!

**Review by gilluminate — CHANGES_REQUESTED** [review]
@guncha code looks great. The failing test should likely pass now if you pull in latest from `main` since that was fixed elsewhere. Also, would you mind taking a moment to update the change in the CHANGELOG.md file? Just take a look at what's already in there and mimic.

**Comment by guncha** [comment]
@gilluminate assuming the checks will pass, this is ready to go! Just needs an approving review to merge.

**Review by gilluminate — APPROVED** [review]
🍎 Looking good!

**Pull request merged**
