### PR TITLE
Updates to consent experience styling

### PR DESCRIPTION
**Pull request by Kelsey-Ethyca**
Closes #[PROD-2224](https://ethyca.atlassian.net/browse/PROD-2224)

### Description Of Changes

Styling changes to the GPC badge, GVL badge, and toggle arrows. 

### Code Changes

* [ ] fides.js css updates to spacing and alignment 

### Steps to Confirm

* [ ] Verify the badges and arrows are aligned, spaced, and sized properly  
* [ ] We will need to verify this will not break any customer's custom CSS

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
  * [ ] if there are any new client scopes created as part of the pull request, remember to update public-facing documentation that references our scope registry
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated
* If there are any database migrations:
  * [ ] Ensure that your downrev is up to date with the latest revision on `main`
  * [ ] Ensure that your `downgrade()` migration is correct and works
    * [ ] If a downgrade migration is not possible for this change, please call this out in the PR description!

https://github.com/user-attachments/assets/de596b3e-6477-4b92-a613-36f73572fa1a

[PROD-2224]: https://ethyca.atlassian.net/browse/PROD-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Kelsey-Ethyca** [comment]
Screenshot 2024-07-18 at 10 19 41 PM
Screenshot 2024-07-18 at 10 21 18 PM

**Comment by Kelsey-Ethyca** [comment]
Screenshot 2024-07-18 at 10 21 43 PM

**Comment by Kelsey-Ethyca** [comment]
Screenshot 2024-07-22 at 11 59 42 AM

**Review by gilluminate — APPROVED** [review]
Nice work! Happy to see the collapse arrow back to normal. :)

**Pull request merged**
