### PR TITLE
Move `packaging` to requirements.txt to fix `check_install`

### LINKED ISSUE #2272: `nox -s check_install` failing on `main`
### Bug Description

The CI check `check_install` started failing today - it looks to be a known version issue with `packaging` -> https://github.com/onicagroup/runway/issues/1729

However ours should be correctly pinned to the lower version

#### Steps to Reproduce

1. `nox -s check_install`
1. Alternatively -> https://github.com/ethyca/fides/actions/runs/3952967562/jobs/6769040134

### Expected behavior

The check should pass

### Screenshots

image

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #2272

### Code Changes

* [x] Move `packaging` to `requirements.txt`

### Steps to Confirm

* [ ] `pip install .`
* [ ] `pip list | grep packaging` returns the correct version

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation:
  * [x] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [x] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

Found in #2263 and #2226

### CODE REVIEW

**Comment by sanders41** [comment]
I did the `pip install .` and verified the package is installed and the correct version, but am still getting the failure with `nox -s check_install`. Is there another step I need?

**Comment by SteveDMurphy** [comment]
> I did the `pip install .` and verified the package is installed and the correct version, but am still getting the failure with `nox -s check_install`. Is there another step I need?

Hmm, that did it for me and [the ci check seems to pass now](https://github.com/ethyca/fides/actions/runs/3953477629/jobs/6769794973) 🤔 I did also trash my virtual environment to try and recreate how the test is run. If not that, maybe something with a specific Python version? I'm on `3.9.15`

**Comment by sanders41** [comment]
I'm 3.10.9. Trying to recreate my virtual environment now to see what that does.

**Review by sanders41 — APPROVED** [review]
My virtual environment is being slow about reinstalling after re-creating. I'm going to go ahead an approve here since it is passing CI with this change, and gets PRs unblocked.

**Comment by sanders41** [comment]
Virtual environment finished and it still failed, but I would still rather merge this and get CI going again.

**Comment by SteveDMurphy** [comment]
> Virtual environment finished and it still failed, but I would still rather merge this and get CI going again.

Hmm, interesting for sure - thanks for the review and taking the time to look at it!

**Pull request merged**
