### PR TITLE
[Unified Fides] Rebuild After Code Changes

### LINKED ISSUE #1179: [Unified Fides] Bringing up Fides Shell after Code Changes
### Bug Description

Bringing up the Fides shell fails when files have changed.  I think I've mainly seen this happen when I had already run the shell with postgres, and I was changing to run the shell with a different database.  I've seen this at least three times now. 

#### Steps to Reproduce

`nox -s dev -- shell postgres` and then change some application files and then run  `nox -s dev -- shell timescale`.  (Reproduction steps may not be entirely accurate, I'm not positive that you have to change the database too.)

```
 => CACHED [backend  2/12] RUN apt-get update &&     apt-get install -y --no-install-recommends     git     make     vim     curl     g++     gnupg     gcc     python3-wheel     && apt-get clean     && rm -rf /var/lib/apt/lis  0.0s
 => CACHED [backend  3/12] COPY optional-requirements.txt .                                                                                                                                                                        0.0s
 => CACHED [backend  4/12] RUN pip install -U pip --no-cache-dir install -r optional-requirements.txt                                                                                                                              0.0s
 => CACHED [backend  5/12] COPY dev-requirements.txt .                                                                                                                                                                             0.0s
 => CACHED [backend  6/12] RUN pip install -U pip --no-cache-dir install -r dev-requirements.txt                                                                                                                                   0.0s
 => CACHED [backend  7/12] COPY requirements.txt .                                                                                                                                                                                 0.0s
 => CACHED [backend  8/12] RUN pip install -U pip --no-cache-dir install -r requirements.txt                                                                                                                                       0.0s
 => [backend  9/12] COPY . /fides                                                                                                                                                                                                  0.4s
 => [backend 10/12] WORKDIR /fides                                                                                                                                                                                                 0.0s
 => ERROR [backend 11/12] RUN git rm --cached -r .                                                                                                                                                                                 0.6s
------
 > [backend 11/12] RUN git rm --cached -r .:
#14 0.609 error: the following files have staged content different from both the
#14 0.609 file and the HEAD:
#14 0.609     tests/ops/integration_tests/test_execution.py
#14 0.609     tests/ops/integration_tests/test_sql_task.py
#14 0.609 (use -f to force removal)
------
executor failed running [/bin/sh -c git rm --cached -r .]: exit code: 1
nox > Command docker build --target=dev --tag ethyca/fides:local . failed with exit code 1
nox > Session dev failed.
```

### Expected behavior

I can bring up a shell when files have changed or I'm changing which databases I want to bring up.

We might just be able to change the line to:
`RUN git rm --cached -rf . `

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by pattisdr**
Closes #1179 

### Code Changes

* [x] Added a force remove when resetting the git cache

### Steps to Confirm

* [ ] Build the shell `nox -s dev -- shell`
* [ ] Make some code changes and commit them
* [ ] Bring down the containers and then build the shell again

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@pattisdr what potential side-effects does this change have?

**Comment by pattisdr** [comment]
Maybe I should just sit on this one for a bit, and watch for it to come back again and make sure I have my "steps to confirm" correct, I have a hard time reproducing the original error on demand, although I have run into this 3+ times now.  

```Dockerfile
RUN git rm --cached -r .  # Recursively clearing the staged files. -f should ignore if the file is updated and staged I think.
RUN git reset --hard  # Resetting both the working index and the staged files
```

As an aside, I'm not sure why we are running the `RUN git rm --cached -r ` line either given that we do a hard reset on the next line.

**Comment by ThomasLaPiana** [comment]
> Maybe I should just sit on this one for a bit, and watch for it to come back again and make sure I have my "steps to confirm" correct, I have a hard time reproducing the original error on demand, although I have run into this 3+ times now.
> 
> The `-rf` fixed once, but perhaps this was a coincidence.
> 
> ```dockerfile
> RUN git rm --cached -r .  # Recursively clearing the staged files. -f should ignore if the file is updated and staged I think.
> RUN git reset --hard  # Resetting both the working index and the staged files
> ```
> 
> As an aside, I'm not sure why we are running the `RUN git rm --cached -r ` line either given that we do a hard reset on the next line.

the `git reset --hard` doesn't work before running the `git rm`, as for some reason `git` will see all files as new or something and not run correctly. We have tests in `ctl` that rely on clean git, and adding the `git rm` fixed it, otherwise they couldn't be run in the docker container.

If there's a more elegant solution to this I'd gladly accept it, but this is where we ended up after trial and error

**Comment by pattisdr** [comment]
OK thanks for the context!

**Comment by ThomasLaPiana** [comment]
> OK thanks for the context! I don't know how to do this better, but if you needed clean git, maybe the "-r" is not always enough to get the clean git. But I'm just going to wait until I see this again!

sounds good! I'll keep an eye out too 👀

**Comment by pattisdr** [comment]
Closing - stale

**Pull request closed without merging**
