### PR TITLE
Dsr error handling configure alerts

### LINKED ISSUE #1218: DSR Notifications (toast)
### USER STORY
As an admin I want a big red banner or some prominent signal on the Fides UI that tells me that the DSR automation is failing/throwing errors. 

I also want to be able to configure alerts - such as to send me an email or a text on my phone when there are failures (I should be able to set a threshold such as if a connector throws errors more than or less than n number of times, start/stop notifying me).

I want to be able to generate a report of the number of errors thrown per connector (type of DSR execution error).

### REQUIREMENTS 
Notifications (email only) and alerts (toast messages) will be used just for DSRs today but plan for a future state where they can be used for other features. 

### AC
- add error toast that displays at the top of the Subjects Request tab that must be dismissed by user

### PR DESCRIPTION
**Pull request by chriscalhoun1974**
Closes #1218 #1491 #1492 

### Code Changes

- Added new release flag called `configureAlertsFlag` to the `flags.json` file 
- Added new menu item `More > Configure alerts` to the Privacy Requests landing page
- When user clicks the `More > Configure alerts` menu item, **Configure alerts and notifications** drawer is displayed which allows a user to configure a list of email recipients, to be notified immediately, and enter threshold number of DSR processing errors.
- If the user has toggled the **Notify me immediately if there are any DSR processing errors** switch to `ON` and clicked the **SAVE** button, there is a polling process for every **15** seconds which invokes the API endpoint (`api/v1/privacy-request?include_identities=true&status=error`). If there are new DSR processing errors in which the total is greater than or equal to the DSR processing errors threshold configured, a toast error notification is displayed with the following text: **DSR automation has failed for [X] privacy request(s). Please review the event log for further details.**

**NOTE** All of the above coding changes are behind the release flag called `configureAlertsFlag` which is located in the `flags.json` file. By default, the `isActive` property is turned to `false`. For testing purposes, you can edit this value to `true`.

### Steps to Confirm

1. On a separate browser tab, log into the **Fides Admin UI** web app.
2. Click the **Connections** nav button.
3. Click the **Create new connection** button.
4. Choose **Mailchimp** connection as an example.
5. Enter the **Connector parameters** and **Dataset configuration** info (For the **Connector parameters** info, enter an invalid Domain, Username, and API Key values). **NOTE**: This is strictly used to have the DSR error for testing purposes.
6. Once your new Connection is created, you will be navigated back to the **Connections** landing page.
7. Navigate to the **Privacy Requests** landing page
8. Click the `More > Configure` alerts menu item located in the upper right hand corner.
9. When the sliding drawer titled **Configure alerts and notifications** is rendered, enter one or more email addresses, toggle the **Notify me immediately if there are any DSR processing errors** to `ON`, accept the default threshold value, and click the **Save** button.
10. On a separate browser tab, log into the **Privacy Center** web app.
11. Create one or more DSR(s) by entering **Name** and **Email** values via the **Access your data** modal and click the **Continue** button.
12. Click the previous **Fides Admin UI** browser tab.
13. Navigate to the **Privacy Requests** landing page.
14. Verify your new DSR(s) from Step 2 have a **NEW** status.
15. For each DSR, you can click the **Approve** button located on the right end of the row when hovered.
16. For each DSR clicked in the previous step, the status should be **ERROR** now.
17. A toast error notification located on the top of the UI screen should now be displayed with the following text: _DSR automation has failed for [X] privacy request(s). Please review the event log for further details._
18. To dismiss the toast error notification, the user must click the **X** icon within the toast notification itself.
19. If the user would like to stop being notified to be alerted via toast notification or email for any DSR processing errors, the user will need to toggle the **Notify me immediately if there are any DSR processing errors** to `OFF` via clicking the `More > Configure` alerts menu item located in the upper right hand corner.

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Screen Shots

Screen Shot 2022-11-30 at 8 47 54 AM
Screen Shot 2022-11-30 at 8 48 32 AM
Screen Shot 2022-11-30 at 8 50 49 AM

### CODE REVIEW

**Comment by sanders41** [comment]
One thing I have noticed while testing this is once you turn messages on, you can't turn them off. If you turn off notifications and remove the email addresses you get an error.

Screen Shot 2022-12-02 at 11 31 08 AM

**Comment by chriscalhoun1974** [comment]
@sanders41 The validation issue you identified has been resolved now.

**Review by sanders41 — APPROVED** [review]
Approving from a functionality standpoint.

**Review by Kelsey-Ethyca — APPROVED** [review]

**Comment by chriscalhoun1974** [comment]
I have removed the `configureAlertsFlag` release flag.

**Pull request merged**
