### PR TITLE
include fides_key in datamap api output

### LINKED ISSUE #987: Include system dependencies in datamap endpoint
### Is your feature request related to a specific problem?

I want to be able to map system dependencies found across my data map

### Describe the solution you'd like

Have the datamap provide the appropriate fides keys and system dependencies as part of the datamap endpoint output

### Describe alternatives you've considered, if any

Just provide the fides keys and require a separate API request to map the system dependencies

### Additional context

This was originally requested by @LKCSmith - please update or modify to make sure the intent is covered and thank you!

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #987

### Code Changes

* [x] Include the `fides_key` for system and dataset rows returned by the `/datamap` enpoint

### Steps to Confirm

* [x] Validate the `fides_key` of items in the data map
* [x] Work with frontend to ensure it works for them

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [x] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

This is not pretty but wanted to get a start out for this quickly as it sounds like a potential blocking item

### CODE REVIEW

**Comment by LKCSmith** [comment]
@SteveDMurphy I really appreciate you getting started on this, despite feeling under the weather, and I hope you are feeling better or at least taking the time to feel better!! 🍵 Let me know when you think this is good for the FE to test with.

**Comment by SteveDMurphy** [comment]
> @SteveDMurphy I really appreciate you getting started on this, despite feeling under the weather, and I hope you are feeling better or at least taking the time to feel better!! 🍵 Let me know when you think this is good for the FE to test with.

Thanks @LKCSmith !! This at least has the fides key(s) for system and dataset included, so that may be enough to start. I am going to experiment with pulling in the system dependencies as well this morning but hoping you can get an early start

**Comment by SteveDMurphy** [comment]
@LKCSmith both `fides_key`'s and `system_dependencies` are now part of the output. I think the output is still technically a comma separated string but I think that should be easily fixed (Assuming it's easier for the frontend to have a list instead of a string) - would love to hear what you get from any testing!

**Comment by LKCSmith** [comment]
@SteveDMurphy Thank you! I'll try this out today 🚀

**Comment by LKCSmith** [comment]
@SteveDMurphy - One last request (if it makes sense to you) - is it possible to also include the `system.description`? If I had this included, I wouldn't need to map through an additional query to link it in the spatial map node. If it doesn't make sense to return it here, then I can do that mapping, but thought this might be more straightforward. What do you think?

**Comment by SteveDMurphy** [comment]
> @SteveDMurphy - One last request (if it makes sense to you) - is it possible to also include the `system.description`? If I had this included, I wouldn't need to map through an additional query to link it in the spatial map node. If it doesn't make sense to return it here, then I can do that mapping, but thought this might be more straightforward. What do you think?

Thanks for the heads up @LKCSmith ! I don't see any issue with including it as well, anything to we can do to make rendering the datamap a bit easier 👍🏽. The only problem I foresee is if there are a large number of rows for a single system (thinking many data categories) we end up duplicating a bunch of data unnecessarily for each row. I think this is likely a problem we can address down the road however and just focus on driving ahead here.

Will get that added either later tonight or first thing in the morning so you can drop that additional query, thanks again!

**Review by ThomasLaPiana — APPROVED** [review]
LGTM! Thanks for the speedy unblocking action here :)

**Comment by SteveDMurphy** [comment]
Thanks for the lightning fast review!! ⚡ ⚡

**Pull request merged**
