### PR TITLE
Add Intel Mac platform support for Docker builds

### LINKED ISSUE #1430: Building the container doesn't work on x86-based Macs
### Bug Description

The platform for Intel Macs wasn't taken into account when handling Docker emulation. A third option needs to be added for that platform

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1430 

### Code Changes

* [x] add a 3rd option to the build matrix
* [x] add an import check for `git` before trying to build prod

### Steps to Confirm

* [ ] someone with an intel mac confirms that this fix works and Docker performance is acceptable

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

This PR adds a third option to handle the machine type for Intel-based Macs. However I'm not sure if the "linux/amd64" platform is performant, but its the closest option that looked right when looking at the platforms provided by `Python` Docker images

### CODE REVIEW

**Comment by NevilleS** [comment]
On my platform a build took 14m10s and `build(prod)` errors. Below is the notes:

My platform:
```
~/git/fides% python3 -m platform
macOS-12.6-x86_64-i386-64bit
```

I used `time` to measure the full build:
```
~/git/fides% time nox -s build
...
nox > Ran multiple sessions:
nox > * build(prod): failed
nox > * build(dev): success
nox > * build(test): success
nox > * build(ui): success
nox > * build(pc): success
nox -s build  12.15s user 13.16s system 2% cpu 14:10.48 total
```

The `build(prod)` error is this:
```
nox > Running session build(prod)
nox > Re-using existing virtual environment at .nox/build-prod.
nox > Session build(prod) raised exception ModuleNotFoundError("No module named 'git'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nox/sessions.py", line 695, in execute
    self.func(session)
  File "/usr/local/lib/python3.9/site-packages/nox/_decorators.py", line 113, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nox/_decorators.py", line 68, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nox/_decorators.py", line 68, in __call__
    return self.func(*args, **kwargs)
  File "/Users/neville/git/fides/noxfiles/docker_nox.py", line 82, in build
    tag(),
  File "/Users/neville/git/fides/noxfiles/docker_nox.py", line 19, in get_current_image
    return f"{IMAGE}:{get_current_tag()}"
  File "/Users/neville/git/fides/noxfiles/constants_nox.py", line 7, in get_current_tag
    from git.repo import Repo
ModuleNotFoundError: No module named 'git'
```

**Review by NevilleS — APPROVED** [review]
This works for me on my Intel Mac 👍 

I suspect the `build(prod)` error is unrelated to this change

**Comment by ThomasLaPiana** [comment]
@NevilleS the build error is related to the `git` module being required locally for this to work. I definitely need to add a user-friendly error message here though!

**Comment by ThomasLaPiana** [comment]
added a module check for git before building the prod container :)

**Pull request merged**
