### PR TITLE
Refactor evaluation logic

### LINKED ISSUE #211: Refactor Evaluation logic
This is by far the most complex area of the codebase currently, and there are some known inefficiencies in those modules. Need to go in and profile that code from performance, readability and complexity perspectives

### LINKED ISSUE #264: Add actionable failure messaging to `evaluate`
While the failure messaging for `evaluate` is descriptive with the policy declaration, system, and rule that's being violated. 

Current state:
```
root@fa175a43c077:/fides/fidesctl# fidesctl evaluate demo_resources
...
Executing evaluations...
{
  "status": "FAIL",
  "details": [
    "Declaration (Collect data for marketing) of System (demo_marketing_system) failed Rule (Reject Direct Marketing) from Policy (demo_privacy_policy)"
  ],
  "message": null
}
```

Providing actionable/meaningful error and failure messaging helps an implementer clearly know next steps to take whether they
1. "broke" the build for first-time implementers
2. are maintaining a fides-annotated project and have now legitimately violated a policy

This issue is to add additional logging to the details node of the failure message here to understand what exactly was failing, for example:

```
root@fa175a43c077:/fides/fidesctl# fidesctl evaluate demo_resources
...
Executing evaluations...
{
  "status": "FAIL",
  "details": [
    "Declaration (Collect data for marketing) of System (demo_marketing_system) failed Rule (Reject Direct Marketing) from Policy (demo_privacy_policy)" because system (demo_marketing_system) contains user.provided.identifiable.contact data
  ],
  "message": null
}
```

There are likely edge cases where this format might not work, but would like to explore the edges of this with the demo/quickstart repo.

### PR DESCRIPTION
**Pull request by earmenda**
Closes  #211
Closes #264 

### Code Changes

* [x] Remove explicit types from fides key population
* [x] Move missing key validation now that FidesKey is reserved for top level model
* [x] Fix evaluation messages for #264
* [x] ~~Reduce number of api calls from evaluate~~

### Steps to Confirm

* [x] New unit tests added for missing key validation
* [x] Existing unit tests test including evaluation 

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Documentation Updated

### Description Of Changes

* The reason that we can now remove the old missing validation and replace it with a much simpler one is that due to a recent change FidesKey is now reserved for top level models. This is how it was meant to be modeled to begin with. 
* Updates to evaluation logic so evaluation can output which fields triggered a failure

### CODE REVIEW

**Comment by earmenda** [comment]
@ThomasLaPiana 

A couple notes on this:
* I worked on trying to reduce the number of api calls from evaluate but unfortunately I couldn't think of a way of getting the resource type when we populate fides keys. I thought originally we could get it from the type in `get_referenced_missing_keys` but this finds nested keys which are not of that type. 
* I wasn't able to get profiling to work by using the `fidesctl` command, this seemed to work alot easier through code
* #264 I can add to this, should be easy

**Comment by earmenda** [comment]
Made code change to address #264

**Comment by ThomasLaPiana** [comment]
@earmenda do we have documentation anywhere about how to auto-generate the migrations? I feel like we should add that in somewhere, just since it is definitely not an obvious thing

**Comment by earmenda** [comment]
@ThomasLaPiana Not at the moment. I can add a new section to the development markdown page. I could see it working under `Write your code` we could add something like `To learn how to migrate the database for schema changes, see the database migration guide` 

It would just be short at the moment since we just need to document something like this:
`alembic revision --autogenerate -m "message"`

I do think in the future there will be more things we will need to document around this though.

**Comment by earmenda** [comment]
@ThomasLaPiana 

After the latest changes this is what the output of a failing evaluation looks like:
```
root@8d4b52631402:/fides/fidesctl# fidesctl evaluate --message "Testing new evaluation output" demo_resources/
Loading resource manifests from: demo_resources/
Taxonomy successfully created.
----------
Processing policy resources...
CREATED 0 policy resources.
UPDATED 0 policy resources.
SKIPPED 1 policy resources.
----------
Processing registry resources...
CREATED 0 registry resources.
UPDATED 0 registry resources.
SKIPPED 1 registry resources.
----------
Processing system resources...
CREATED 0 system resources.
UPDATED 0 system resources.
SKIPPED 2 system resources.
----------
Processing dataset resources...
CREATED 0 dataset resources.
UPDATED 0 dataset resources.
SKIPPED 1 dataset resources.
----------
Loading resource manifests from: demo_resources/
Taxonomy successfully created.
Evaluating the following Policies:
- demo_privacy_policy
----------
Checking for missing resources...
Executing Policy evaluation(s)...
Sending the evaluation results to the server...
{
  "fides_key": "43551730_cb99_4dfa_888a_81c53ac9c72f",
  "status": "FAIL",
  "violations": [
    {
      "violating_attributes": {
        "data_category": "user.provided.identifiable.contact",
        "data_subject": "customer",
        "data_qualifier": "aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified",
        "data_use": "advertising"
      },
      "detail": "Declaration (Collect data for marketing) of System (demo_marketing_system) failed Rule (Reject Direct Marketing) from Policy (demo_privacy_policy). Violated usage of user.provided.identifiable.contact data qualified by aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified for data use advertising and subject customer"
    }
  ],
  "message": "Testing new evaluation output"
}
```

A few callouts on the current state though:
* I did not create a new high level object for Violation. This might be something we need in the future though if we need to reference violations by an id. Let me know if you think we should just do this now. 
* My first stab at this was harder than I expected and it made the `compare_rule_to_declaration` a little more complicated than I was hoping. Now that we care about which keys fail, the old logic doesn't work as nicely.  I can try to simplify it today if i find some time.

**Comment by ThomasLaPiana** [comment]
@earmenda that output looks great! going to give the code another review and we'll get this merged, this definitely satisfies the requirements

**Review by ThomasLaPiana — APPROVED** [review]
LGTM! Tested locally, all was working.

**Comment by ThomasLaPiana** [comment]
@earmenda you're good to merge when ready!

**Comment by earmenda** [comment]
@ThomasLaPiana 

Thanks for the review. I just pushed a few other changes 

- Added a `database_migration.md` page to document how to migrate the database
- Refactored `compare_rule_to_declaration` a bit so it's more straightforward . Also added some more comments
- Improved tests for `compare_rule_to_declaration` to check values
- ViolationAttributes now has a list of categories / uses / subjects
- Touched up the detail string so it's a little more consistent

This is ready for merge so if you don't see anything you'd like to see changed then feel free to merge it in or approve again. 


```
root@51540454edf5:/fides/fidesctl# fidesctl evaluate demo_resources/
Loading resource manifests from: demo_resources/
Taxonomy successfully created.
----------
Processing policy resources...
CREATED 0 policy resources.
UPDATED 0 policy resources.
SKIPPED 1 policy resources.
----------
Processing system resources...
CREATED 0 system resources.
UPDATED 0 system resources.
SKIPPED 2 system resources.
----------
Processing registry resources...
CREATED 0 registry resources.
UPDATED 0 registry resources.
SKIPPED 1 registry resources.
----------
Processing dataset resources...
CREATED 0 dataset resources.
UPDATED 0 dataset resources.
SKIPPED 1 dataset resources.
----------
Loading resource manifests from: demo_resources/
Taxonomy successfully created.
Evaluating the following policies:
- demo_privacy_policy
----------
Checking for missing resources...
Executing Policy evaluation(s)...
Sending the evaluation results to the server...
{
  "fides_key": "57118033_1eae_4973_bbce_df3cc0898d02",
  "status": "FAIL",
  "violations": [
    {
      "violating_attributes": {
        "data_categories": [
          "user.provided.identifiable.contact",
          "user.provided.identifiable"
        ],
        "data_subjects": [
          "customer"
        ],
        "data_uses": [
          "advertising"
        ],
        "data_qualifier": "aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified"
      },
      "detail": "Declaration (Collect data for marketing) of system (demo_marketing_system) failed rule (Reject Direct Marketing) from policy (demo_privacy_policy). Violated usage of data categories (user.provided.identifiable.contact,user.provided.identifiable) with qualifier (aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified) for data uses (advertising) and subjects (customer)"
    }
  ],
  "message": "Testing evaluation output"
}
```

**Pull request merged**
