### PR TITLE
Add pre-commit & pre-push Gitleaks secrets detection hooks

### LINKED ISSUE #1497: Add a pre-commit check for secrets
### Is your feature request related to a specific problem?

We want to avoid accidentally committing secrets to the repo

### Describe the solution you'd like

Add a pre-commit task that scans for secrets. We should additionally leverage the `noxfile` to verify that developers have this enabled.

### Describe alternatives you've considered, if any

Not sure what other options we have besides pre-commits here, or what might be better

### PR DESCRIPTION
**Pull request by daveqnet**
Closes #1497 

### Code Changes

* [ ] Add a pre-commit hook for Gitleaks secrets detection
* [ ] Add a pre-push hook for Gitleaks secrets detection

### Steps to Confirm

* [ ] [Install pre-commit locally](https://pre-commit.com/#install)
* [ ] [Install gitleaks locally](https://github.com/zricethezav/gitleaks/blob/master/README.md#getting-started)
* [ ] In the root of the fides repo, run
   * [ ] `pre-commit install --hook-type pre-commit` if you want to use the pre-commit hook
   * [ ] `pre-commit install --hook-type pre-push` if you want to use the pre-push hook
* [ ] Create any file with a fake secret e.g. `discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ'` that will be detected by Gitleaks
* [ ] Try to commit or push, as applicable. The commit/push should fail.

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

The purpose of these changes is to enable devs to detect hardcoded secrets before accidentally publishing them. It leverages [the pre-commit framework](https://pre-commit.com/) and [Gitleaks](https://github.com/zricethezav/gitleaks).

### CODE REVIEW

**Comment by daveqnet** [comment]
@sanders41, @ThomasLaPiana, @ssangervasi, and @allisonking : would love any and all feedback before this gets merged. 🙏

**Comment by sanders41** [comment]
When I run `gitleaks detect --report-path gitleaks-report.json` there are findings (all tests and not real leaks so not a worry), then when I run `pre-commit run --all` there are no findings. Is this expected? I don't see a config file that would be excluding findings in pre-commit.

**Comment by daveqnet** [comment]
Hi @sanders41, just checking: did you run `pre-commit install --hook-type pre-push` before testing the pre-push hook?

Here's a successful demo I just ran locally (feel free to test with the dummy/fake Discord secret I tested with):

```shell
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks ❯ pre-commit install --hook-type pre-commit --hook-type pre-push
pre-commit installed at .git/hooks/pre-commit
pre-commit installed at .git/hooks/pre-push
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks ❯ echo discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ' > SOMEFILE.md
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks ?1 ❯ git add .
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks +1 ❯ git commit -m "This should trigger the pre-commit hook and fail"
gitleaks-pre-commit......................................................Failed
- hook id: gitleaks-pre-commit
- exit code: 1

Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:14PM INF 1 commits scanned.
2:14PM INF scan completed in 61.5ms
2:14PM WRN leaks found: 1

~/projects/github/ethyca/fides daveqnet-precommit-gitleaks +1 ❯ SKIP=gitleaks-pre-commit git commit -m "Okay, let me skip the pre-commit hook and test the pre-push hook instead"
gitleaks-pre-commit.....................................................Skipped
[daveqnet-precommit-gitleaks e08fab2e] Okay, let me skip the pre-commit hook and test the pre-push hook instead
 1 file changed, 1 insertion(+)
 create mode 100644 SOMEFILE.md
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks ⇡1 ❯ git push
gitleaks-pre-push........................................................Failed
- hook id: gitleaks-pre-push
- exit code: 1

Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Commit:      e08fab2e91bf2b51d63ec0868610951be85860e3
Author:      Dave Quinlan
Email:       83430497+daveqnet@users.noreply.github.com
Date:        2022-11-15T14:15:26Z
Fingerprint: e08fab2e91bf2b51d63ec0868610951be85860e3:SOMEFILE.md:discord-client-secret:1

2:15PM INF 4 commits scanned.
2:15PM INF scan completed in 59.9ms
2:15PM WRN leaks found: 1

error: failed to push some refs to 'https://github.com/ethyca/fides.git'
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks ⇡1 ❯ git reset --hard HEAD~1
HEAD is now at 4e269573 Clarified usage instructions
```

**Comment by daveqnet** [comment]
Here's the result of a `pre-commit run --all`

```shell
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks ❯ echo discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ' > SOMEFILE.md                                   
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks ?1 ❯ git add .                                                                                                       
~/projects/github/ethyca/fides daveqnet-precommit-gitleaks +1 ❯ pre-commit run --all
gitleaks-pre-commit......................................................Failed
- hook id: gitleaks-pre-commit
- exit code: 1

Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 64.9ms
2:21PM WRN leaks found: 1
Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 70.7ms
2:21PM WRN leaks found: 1
Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 67.3ms
2:21PM WRN leaks found: 1
Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 63.7ms
2:21PM WRN leaks found: 1
Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 67.7ms
2:21PM WRN leaks found: 1
Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 64.5ms
2:21PM WRN leaks found: 1
Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 68ms
2:21PM WRN leaks found: 1
Finding:     discord_client_secret = REDACTED
Secret:      REDACTED
RuleID:      discord-client-secret
Entropy:     4.413910
File:        SOMEFILE.md
Line:        1
Fingerprint: SOMEFILE.md:discord-client-secret:1

2:21PM INF 1 commits scanned.
2:21PM INF scan completed in 71.2ms
2:21PM WRN leaks found: 1
```

I wonder why it's showing the same secret being detected multiple times, hmmm.

**Comment by sanders41** [comment]
I was testing the pre commit version of the hook

```console
~/development/python/fides ❯  daveqnet-precommit-gitleaks ❯ 🐍 v3.10.8 (.venv) ✦ ❯ pre-commit install
pre-commit installed at .git/hooks/pre-commit

~/development/python/fides ❯  daveqnet-precommit-gitleaks ❯ 🐍 v3.10.8 (.venv) ✦ ❯ echo discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ' > SOMEFILE.md

~/development/python/fides ❯  daveqnet-precommit-gitleaks [?] ❯ 🐍 v3.10.8 (.venv) ✦ ❯ pre-commit run --all
gitleaks-pre-commit......................................................Passed
```

**Comment by sanders41** [comment]
For those following along it does work with pre-commit after staging the file.

**Review by sanders41 — APPROVED** [review]

**Pull request merged**
