### PR TITLE
Fix AWS Scan Test

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #

Newly-created test resources: https://ethyca.atlassian.net/browse/OPS-346?focusedCommentId=36117

### Code Changes

* [x] Update the expected objects for the AWS system scan test
* [x] Update Secrets for the actions

### Steps to Confirm

* [x] `ctl-external` tests pass

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded

### Description Of Changes

Update the _expected_ resources within our external tests to match the _reality_ of what actually exists in those accounts.

Additionally, @daveqnet has created a sequestered area for our tests so that we shouldn't have to worry about resource drift/changes impacting these tests in the future.

### CODE REVIEW

**Comment by daveqnet** [comment]
> fyi @daveqnet I'm going to fix this here

Gotcha! The thing we'll need to work on is IAM and which creds/secrets are being used by this test in CI. I wasn't able to puzzle this out from the code - do you know?

**Comment by ThomasLaPiana** [comment]
> > fyi @daveqnet I'm going to fix this here
> 
> Gotcha! The thing we'll need to work on is IAM and which creds/secrets are being used by this test in CI. I wasn't able to puzzle this out from the code - do you know?
> 
> [edit: obviously just looking for their parameter names in GH Actions secrets, not the actual secret values]

I'm not sure how to figure that out either 🤔 if it isn't obvious maybe we should just create new creds for this test env specifically?

**Comment by daveqnet** [comment]
> I'm not sure how to figure that out either 🤔 if it isn't obvious maybe we should just create new creds for this test env specifically?

Okay, yep, let's do it, @ThomasLaPiana. I will message you privately to discuss.

**Review by adamsachs — APPROVED** [review]
thank you @ThomasLaPiana and @daveqnet for the diligence in clearing this up! 🎊

**Review by SteveDMurphy — APPROVED** [review]

**Comment by SteveDMurphy** [comment]
> CI failures for external saas tests seem unrelated, though we do have to clean _that_ up at some point. not relevant here though!

We created this #3278  recently as well for saas connectors too @adamsachs - agree hopefully soon!

**Comment by ThomasLaPiana** [comment]
thank you all! team effort here 🙂

**Pull request merged**
