### PR TITLE
Unify Ops/Ctl configuration

### LINKED ISSUE #1012: Merge config logic for ops/ctl on the `unified-fides` branch
### Is your feature request related to a specific problem?

Currently each config gets built separately from discrete config files (`fidesops.toml` and `fidesctl.toml`)

### Describe the solution you'd like

These should be merged use a single set of logic built from a single `fides.toml` file. The behavior should largely default to the current `fidesctl` behavior, i.e. assuming the `.fides/` is the directory where the config file will live.

### Describe alternatives you've considered, if any

Continuing to use separate config files, but this doesn't feel right given all of the work being done to unify the product.

### Additional context

Probably best to wait until #1011 gets merged so that we can make sure we don't break anything when we implement the merger

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1012 

### Code Changes

* [x] merge the ops config into the ctl config logic
* [x] update the default config path to `fides.toml`
* [x] remove `enabled` field from the `database` config section (it doesn't make much sense to run the webserver without a database)
* [x] update fidesops code to use `config.cli.server_port` instead of a top-level `port` value
* [x] open an issue to merge ops integration config into the ctl config logic

### Steps to Confirm

* [ ] tests pass 🚀 

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

This PR deduplicates the config logic for ctl/ops as well as streamlines some of the ops-specific logic for configuration.

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@sanders41 @seanpreston can you give me a little bit of background on the thinking behind ops having a separate config file for integrations?

**Comment by sanders41** [comment]
It just has the extra configs not normally used. I haven't tried, but seems like it would be ok to have that in the main config and just not used when not needed.

**Comment by ThomasLaPiana** [comment]
> It just has the extra configs not normally used. I haven't tried, but seems like it would be ok to have that in the main config and just not used when not needed.

Ok just wanted to check. @earmenda designed a really clever solution in `ctl` to handle storing credentials so I'll probably piggy-back it onto that

**Comment by ThomasLaPiana** [comment]
quick update here! Everything looks pretty good but now I'm seeing test failures related to fideslog, it was also preventing the server from starting. Will need to investigate

**Comment by ThomasLaPiana** [comment]
should be ready to merge after this pass (with the expected failures)

**Pull request merged**
