### PR TITLE
Remove optional-requirements.txt file

### LINKED ISSUE #732: FastAPI version in setup.py and optional-requirements.txt are different
### Bug Description

In `setup.py` the version of FastAPI that is installed is `0.75.2`, but the version in `optional-requirements.txt` is `0.77.1`. All of the requirements in `optional-requirements.txt` are also in `setup.py` so `optional-requirements.txt` seems redundant. The `Dockerfile` does have a step to copy and install `optional-requirements.txt`. In the build step if the build is a dev build it installs with `pip install -e ".[all,mssql]"` so this should get all of the optional dependencies installed. If in production mode it installs with `pip install dist/fidesctl-*.tar.gz` so it doesn't look like it needs the optional dependencies.

I think we should remove the `optional-requirement.txt` file to prevent this issue.

#### Steps to Reproduce

Compare FastAPI version in `setup.py` and `optional-requirements.txt`.

### Expected behavior

There shouldn't be a version mismatch.

### Screenshots

N/A

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

N/A

### PR DESCRIPTION
**Pull request by sanders41**
Closes #732

### Code Changes

* [x] Removed `optional-requirements.txt`
* [x] Bumped fastapi to 0.77.1 in `setup.py`
* [x] Removed the copy and install steps of `optional-requirements.txt` in the `Dockerfile`

### Steps to Confirm

* [x] Run `nox -s build_local`
* [x] Run test suite

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### CODE REVIEW

**Comment by sanders41** [comment]
When I run the tests locally they pass. Any thoughts why CI would be different?

**Comment by sanders41** [comment]
I think it is because CI is installing in production mode `RUN python setup.py sdist`. I think this means some of the optional requirements aren't actually optional?

**Comment by SteveDMurphy** [comment]
@sanders41 I need to check back through the git history but I feel like `optional-requirements.txt` may have originally been part of a docker performance enhancement as well (to improve build times) and maybe not actually optional... validating quickly to see but taking longer than I expected 🤞🏽

**Comment by sanders41** [comment]
@SteveDMurphy yes, this is a downside I thought of to removing it. It will mean the installed requirements won't be cached. The plus side is there is there would be no more chance for conflicting dependencies, so there are for sure advantages and disadvantages to each.

**Comment by sanders41** [comment]
> of course, found it immediately after -> https://github.com/ethyca/fides/pull/479

So this brings 2 questions. Is there a way we can ensure the dependencies don't get out of sync? Should the optional requirements be in `requirements.txt` if tests fail without them (or at least some of them)?

**Comment by ThomasLaPiana** [comment]
> @SteveDMurphy yes, this is a downside I thought of to removing it. It will mean the installed requirements won't be cached. The plus side is there is there would be no more chance for conflicting dependencies, so there are for sure advantages and disadvantages to each.

In this case I think that optimizing for a better developer experience is worth it, at least for now. The reason this got out of sync in the first place was by me not being careful when merging dependabot PRs, which shouldn't be an issue anymore :) 

To answer your other questions, yes we deliberately decided to make a very lightweight version of fidesctl that anyone could install. On a small tangent, I'm going to be opening up an issue that updates the docs and recommends installing fidesctl via `pipx` so make this much less of an issue, maybe we can do some requirements clean-up at that time

**Comment by sanders41** [comment]
So for now I will close this one and open a new PR to get the FastAPI versions in sync. Does that sound like a good plan?

**Comment by ThomasLaPiana** [comment]
@sanders41 perfect, appreciated!

**Pull request closed without merging**
