### PR TITLE
Editing a dataset field or collection's data category

### PR DESCRIPTION
**Pull request by allisonking**
Closes https://github.com/ethyca/fides/issues/704

### Code Changes

* [x] Add a data category checkbox tree to a dropdown in the dataset field and dataset collection edit forms
* [x] Add a DataCategoryTag component with an optional `onClose` so the tag can also control checked state
* [x] Remove data category as a default in the column list, per the design

### Steps to Confirm

* [x] Head over to http://localhost:3000/dataset/demo_users_dataset, click on a field, and start editing data categories

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

https://user-images.githubusercontent.com/24641006/172943450-da2e59c6-bd6b-435b-9de6-52425096b337.mov

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
`Eduardo!!` 😂

**Review by ThomasLaPiana — APPROVED** [review]
Can't comment on the code itself, but I played around with this locally and it all worked!

**Comment by mfbrown** [comment]
@allisonking Let's do one more pass on this UX before we merge this. In the provided example, after you clear all categories, then select `system.authentication` we should only be persisting the category `system.authentication` not also `system`. I think we're almost there, just need to sort through the UX around unselecting a child category.

**Comment by allisonking** [comment]
> @allisonking Let's do one more pass on this UX before we merge this. In the provided example, after you clear all categories, then select `system.authentication` we should only be persisting the category `system.authentication` not also `system`. I think we're almost there, just need to sort through the UX around unselecting a child category.

@mfbrown I'm working on fixing that logic in https://github.com/ethyca/fides/issues/743 (which should probably be renamed.... but see the comment there). There's quite a few logic changes needed, so it'll be a separate PR from this one, but yeah you're totally right!

**Comment by allisonking** [comment]
See https://github.com/ethyca/fides/pull/760 for the checkbox behavior changes 🏁

**Pull request merged**
