### PR TITLE
Add frontend build to the docker build

### PR DESCRIPTION
**Pull request by allisonking**
Closes https://github.com/ethyca/fides/issues/663

### Code Changes

* [x] Convert the Next app from dynamic to static (more details in context below)
* [x] Add an npm script for copying the production build
* [x] Build the static assets in the dockerfile
* [x] Copy the static assets to the right place in the dockerfile

### Steps to Confirm

* [x] Run `nox -s build_local_prod`
* [x] Comment out the volume mount in `docker-compose.yaml` to be sure that what we are looking at is in the Docker container and not local
* [x] Run `docker-compose up fidesctl` (note: `nox -s api` will not work, since that builds the local, non-prod image, which does not do the js build)
* [x] Navigate to localhost:8080 for our bare bones UI 🎉 

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation Updated:
  - [x] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

A summary of a discussion with @NevilleS and @elliotbonneville around how we are using the Next node server:

There are two ways Next can run: static or dynamic. The app is currently configured to run in a dynamic way, which means it needs to use the Next server (node). This allows for some really nice UX features, such as image optimization and server side rendering. However, if we want to use our Python server to host the application (so that we can run one command i.e. `fidesctl webserver`) then we need Next to be in static mode so that we do not also have to run a node server. 

Down the line, we probably _do_ want the node server for all of the nice UX. However, for v1 we are going to focus work just on having stable frontends that can be spun up easily, and avoid going down the devops path of working with multiple servers, perhaps with routing by nginx, until further down the line.

Right now, there are only two Next dynamic features we use:
1. Image optimization. This is easy to replace by swapping out their `<Image>` component for just the standard html `` tag
2. Authentication. This work is in flight this week, so we will want to pull that in later so we can remove calls to `getServerSideProps`
These are removed in https://github.com/ethyca/fides/pull/664/commits/41e40c4d7038a5a974c818b54efb35345360df05

### CODE REVIEW

**Review by ThomasLaPiana — APPROVED** [review]
LGTM! Tested it locally and saw the wonderful UI

**Comment by ThomasLaPiana** [comment]
@allisonking this should be another issue, but do you think we should add to the docker compose command eventually and have a node container running for development? or is running npm locally the typical way to develop FE?

**Comment by allisonking** [comment]
> @allisonking this should be another issue, but do you think we should add to the docker compose command eventually and have a node container running for development? or is running npm locally the typical way to develop FE?

In my experience I've always run it locally and it's worked out really well. But maybe we need to add some documentation to do that, since it'd be separate from where all the nox commands live?

**Comment by ThomasLaPiana** [comment]
> > @allisonking this should be another issue, but do you think we should add to the docker compose command eventually and have a node container running for development? or is running npm locally the typical way to develop FE?
> 
> In my experience I've always run it locally and it's worked out really well. But maybe we need to add some documentation to do that, since it'd be separate from where all the nox commands live?

even if its running locally I'm going to be a stickler and say it needs to still be a nox command somehow (for instance, most of our nox commands use `external` and call out to the local docker CLI anyway)

this can definitely wait for another issue though :)

**Pull request merged**
