### PR TITLE
Fix seed test data

### LINKED ISSUE #1150: seed_test_data errors
### Bug Description

Running `nox -s seed_test_data` throws the following stack trace

```console
⠿ fides-ui Error                                                                                                                               0.6s
Error response from daemon: manifest for ethyca/fides:local-ui not found: manifest unknown: manifest unknown
nox > Session seed_test_data raised exception Exception('Error executing command: docker compose -f docker-compose.yml -f docker/docker-compose.integration-postgres.yml up -d')
Traceback (most recent call last):
  File "/Users/paul/development/python/fides/.venv/lib/python3.9/site-packages/nox/sessions.py", line 728, in execute
    self.func(session)
  File "/Users/paul/development/python/fides/.venv/lib/python3.9/site-packages/nox/_decorators.py", line 75, in __call__
    return self.func(*args, **kwargs)
  File "/Users/paul/development/python/fides/noxfiles/utils_nox.py", line 33, in seed_test_data
    run_infrastructure(datastores=["postgres"], run_create_test_data=True)
  File "/Users/paul/development/python/fides/noxfiles/run_infrastructure.py", line 98, in run_infrastructure
    return _run_create_test_data(path, COMPOSE_SERVICE_NAME)
  File "/Users/paul/development/python/fides/noxfiles/run_infrastructure.py", line 169, in _run_create_test_data
    _run_cmd_or_err(f"docker compose {path} up -d")
  File "/Users/paul/development/python/fides/noxfiles/run_infrastructure.py", line 146, in _run_cmd_or_err
    raise Exception(f"Error executing command: {cmd}")
Exception: Error executing command: docker compose -f docker-compose.yml -f docker/docker-compose.integration-postgres.yml up -d
nox > Session seed_test_data failed.
```

#### Steps to Reproduce

1. Run `nox -s "build(dev)"`
1. Run `nox -s seed_test_data`

### Expected behavior

Should run without error.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: unified fides
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by sanders41**
Closes #1150 

### Code Changes

* [ ] fix the database functions used in `create_test_data.py`

### Steps to Confirm

* [ ] running `nox -s seed_test_data` works

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

_Write some things here about the changes and any potential caveats_

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
the problem lies here, where it tries to load policies into the application database:

```
DETAIL:  Failing row contains (pol_d830faa7-9f60-418f-891d-f653b7754437, 2022-09-30 19:29:58.366689+00, 2022-09-30 19:29:58.366689+00, null, delete, null, null, null).

[SQL: INSERT INTO policy (id, name, key, drp_action, execution_timeframe, client_id) VALUES (%(id)s, %(name)s, %(key)s, %(drp_action)s, %(execution_timeframe)s, %(client_id)s)]
[parameters: {'id': 'pol_d830faa7-9f60-418f-891d-f653b7754437', 'name': None, 'key': 'delete', 'drp_action': None, 'execution_timeframe': None, 'client_id': None}]
```

on line ~171 of `create_test_data.py`

**Comment by ThomasLaPiana** [comment]
@sanders41 if you can verify that this works on fidesops, than I would say either a migration got missed, or maybe the model itself didn't get updated in the code? There have been quirks with this 2nd merge where code changes didn't come over as expected and we've had to copy/paste directly from fidesops

**Comment by sanders41** [comment]
I just verified it is running without error on fidesops. Thanks for the pointer, I'll look at the migrations.

**Comment by ThomasLaPiana** [comment]
> I just verified it is running without error on fidesops. Thanks for the pointer, I'll look at the migrations.

got it, gotta be a diff somewhere throwing it off then

**Comment by sanders41** [comment]
Closing in favor of #1280

**Pull request closed without merging**
