### PR TITLE
Release 2.5.0

### PR DESCRIPTION
**Pull request by SteveDMurphy**
### General

- [x] Quickstart verified working and up-to-date
- [x] Add any new tables/columns to the [database diagram](https://github.com/ethyca/fides/blob/5a485387d8af247ec6479e4115088cbbb8394d77/docs/fides/docs/development/update_erd_diagram.md) if they have not already been added
    - To check for the new tables/columns that have been added in the release, look for new migration files in the `src/fides/api/ctl/migrations` directory and inspect their contents
    - If found, look at the latest database diagram, and check whether it contains the tables/columns that were added in these migrations
    - If the diagram is not up to date, follow the steps in the link above to generate a new database diagram with the up-to-date schema, ensuring that all tables and their relationships can be clearly seen
- [x] `nox -s test_env` works (verify the admin UI, privacy center, CLI and webserver)
- [x] `nox -s "build(sample)"` works on the release branch, creating the sample images (this is also prereq for `fides deploy up`)
- [x] `fides deploy up --no-pull` works using the images built in previous step (verify the admin UI, privacy center, CLI and webserver)

```
mkdir ~/fides-2-1-0-test
cd ~/fides-2-1-0-test
python3 -m venv venv
source venv/bin/activate
pip install git+https://github.com/ethyca/fides.git@<branch>
fides deploy up --no-pull
fides status
fides deploy down
rm -rf ~/fides-2-1-0-test
exit 
```

Next, run the following checks against the environment you've spun up using `fides deploy up --no-pull`:

### API

- [x] Verify that the generated API docs are correct
- [x] Verify that the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### CLI

Run these from within `nox -s dev -- shell`

- [x] Run a `fides push`
- [x] Run a `fides pull`
- [x] Run a `fides evaluate`
- [x] Generate a dataset with `fides generate dataset db --credentials-id app_postgres test.yml`
- [x] Scan a database with `fides scan dataset db --credentials-id app_postgres`

### Admin UI

- [x] Every navigation button works
- [x] DSR approval succeeds
- [x] DSR execution succeeds

### Privacy Center

- [x] Every navigation button works
- [x] DSR submission succeeds
- [x] Consent request submission succeeds

### Documentation

- [x] Verify that the CHANGELOG is formatted correctly and clean up verbiage where needed
- [x] Verify that the CHANGELOG is representative of the actual changes

## Post-Release Steps

- [x] Verify the ethyca-fides release is published to PyPi: <https://pypi.org/project/ethyca-fides/#history>
- [x] Verify the fides release is published to DockerHub: <https://hub.docker.com/r/ethyca/fides>
- [x] Verify the fides-privacy-center release is published to DockerHub: <https://hub.docker.com/r/ethyca/fides-privacy-center>
- [x] Verify the fides-sample-app release is published to DockerHub: <https://hub.docker.com/r/ethyca/fides-sample-app>
- [x] Smoke test the PyPi & DockerHub releases with a clean `pip install ethyca-fides` and `fides deploy up`

### CODE REVIEW

**Comment by SteveDMurphy** [comment]
@NevilleS - can we confirm if there should be a `latest` tag for the `fides-privacy-center`? It looks like it hasn't been updated in a few months and no similar tag exists for `fides-sample-app`

**Comment by NevilleS** [comment]
Thanks @SteveDMurphy - I'd actually prefer we publish `:latest` for all our images:
* `fides`
* `fides-privacy-center`
* `fides-sample-app`

It's a known issue that we weren't publishing `latest` but I don't think we ticketed it - whoops.

**Review by NevilleS — APPROVED** [review]
LGTM, thanks!

**Comment by SteveDMurphy** [comment]
`latest` pushed manually for both and #2301 opened - thanks!

**Pull request merged**
