### PR TITLE
Unify ops/ctl web applications

### LINKED ISSUE #1009: Merge ops/ctl admin UIs
### Is your feature request related to a specific problem?

Now that the repos are merged, we'll need to update the front-end to let users navigate the full UI for both applications

### Describe the solution you'd like

A single navigation page for all UIs

### Additional context

We've already put in a request for a hifi design for this

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1009 

### Code Changes

* [x] do another merge of fidesops/main
* [x] move all of the required `ops_main.py` logic into `main.py`
* [x] fix `policy` & `policy webhook` endpoint clashes
* [x] fix `user` duplicated endpoints
* [x] dedupe health endpoint
* [ ] get all of the tests passing
* [x] copy over all of the required secrets for GH actions
* [ ] deduplicate anything that makes sense to deduplicate related to server infra/configuration

### Steps to Confirm

* [ ] tests pass 🚀 

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

These changes are the lynchpin of the `Unified Fides` ™️  project, as this PR fully merges both applications into a single webserver. Further work will be done down the line to continue deduplicating certain code and cleaning things up, however with this change ctl & ops will share a single webserver + database

This PR makes some choices around which pieces to take from which server implementation for merging into a single `main.py` file, so any reviews should mostly focus on the `main.py` changes

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
mental note to self + others:

When dealing with two different heads in alembic migrations, the command to merge them is:
`alembic merge heads -m "merge D and F"`

This will then create a `merge` revision

**Comment by ThomasLaPiana** [comment]
most tests are passing at this point, but there are a few tests in each that need to get fixed

**Comment by ThomasLaPiana** [comment]
updated the postgres error test and confirmed that there was a change in psycopg2 error messaging: https://www.psycopg.org/docs/news.html#what-s-new-in-psycopg-2-9-2

**Comment by ThomasLaPiana** [comment]
@sanders41 @seanpreston is there a hard rule that fidesops (and therefore unified fides) needs to be able to run without a database? Is this to make it easier to get up and running for demos or do you foresee situations where someone would want to deploy fidesops in prod without a database?

**Comment by sanders41** [comment]
I don’t know of a reason a database wouldn’t be used. Almost every route accesses the database so it wouldn’t be very useful without it.

**Comment by ThomasLaPiana** [comment]
Update:
* Still 4 failing tests on Ops Unit tests, looks like it has something to do specifically with policy webhooks that touch the database
* Still 7 failing tests on Ops Integration, all in `request_runner_service_test.py`

**Comment by sanders41** [comment]
It is unrelated to the test failures, but one thing I noticed looking into it is a lot of tests aren't going to run at all with this setup. Tests here are being run with a specific mark `-m unit`, `-m integration`, etc. Unit tests used to run with `-m not integration and not integraton_external and not integration_sass`. With this new setup any test that doesn't have a mark will be skipped, which will be a lot.

It seems risky to only run marked tests for this very reason. If tests aren't marked they get skipped and no one will ever know.

**Comment by ThomasLaPiana** [comment]
@sanders41 good catch, I think this is how it works on fidesops currently though?

**Comment by sanders41** [comment]
You are right, sorry. When I first looked at it I thought it ran with `nox -s "pytest(unit)"`, but that is wrong, it uses `nox -s pytest_unit` so it still has the old behavior.

**Comment by ThomasLaPiana** [comment]
_Note_: the root cause of most of these test failures is a differing auth key, so in most places the `ctl` config needs to be imported and then `config.security.app_encryption_key` changes to `ctl_config.app.encryption_key`

**Comment by ThomasLaPiana** [comment]
the final test errors here are in the `request_runner_service_test.py` file, not sure what's breaking here so I'm going through and trying to carefully discern why some tests in that file are passing while others are failing

**Comment by ThomasLaPiana** [comment]
so looking at the test failures, it doesn't make much sense...I've printed out the values for the failing postgres test and they are as follows:

```
The customer table after deletion:
[(2, 'Jill Customer'), (3, 'Jane Customer'), (1, None)]
Looking for customer_id: 1
In row: (2, 'Jill Customer')
Looking for customer_id: 1
In row: (3, 'Jane Customer')
Looking for customer_id: 1
In row: (1, None)
```

As can be seen, the `id` absolutely exists in the row, but for some reason it isn't matching. Seems like good news as this seems to suggest there is no larger issue here other than maybe a small code fix in the test itself

**Comment by ThomasLaPiana** [comment]
I fixed the failing tests but I don't quite understand why they broke in the first place @sanders41 

The solution was that the comparison wasn't working, but it seemed valid to me 🤔 

This is what I used that works:
`if customer_id == row.id:`

This is what was there previously that didn't work but I'm not sure why:
`if customer_id in row:`

**Comment by ThomasLaPiana** [comment]
all non external/saas tests are passing! 

next step is to copy over all of the secrets that ops needs

**Comment by ThomasLaPiana** [comment]
@sanders41 @seanpreston can you help me get the secrets copied over? I couldn't find them in 1pass under the same name, and those are the last tests left to check

**Comment by sanders41** [comment]
Very weird on the comprehension check. Every reason I can think of that would make `if customer_id in row:` fail would also make `if customer_id == row.id:` fail. Really `if customer_id == row.id:` is more strict so if it works lets go with it.

@eastandwestwind can you help with the secrets? I think these will be the vault secrets.

**Comment by ThomasLaPiana** [comment]
State of the PR:

* Ops External Integration tests have 2 failing Snowflake tests
* Ops External SaaS tests have 2 failing Hubspot tests

I'm going to merge now, as these tests shouldn't hold up this PR or the rest of the work. They can be fixed in a smaller PR

**Pull request merged**
