### PR TITLE
small release checklist updates

### LINKED ISSUE #2074: Tweaks to release checklist doc
### Docs Update Description

Based on running through the `fides` `2.3.0` release process, I noticed some things we could tweak or elaborate on, to make the process abundantly clear!

### Additional context

Nothing major, generally the steps were pretty clear.

### PR DESCRIPTION
**Pull request by adamsachs**
Closes #2074 

### Code Changes

* minor updates to release checklist doc for clarity

-- added a few reviewers for redundancy, don't need a review from everyone!

### CODE REVIEW

**Comment by sanders41** [comment]
All the changes look good to me. One more thing we talked about that would have been nice is a link to the postman collection. 

```markdown
- [ ] Verify that the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated
```

**Comment by adamsachs** [comment]
good call @sanders41 , thanks for that! added the update in a new commit

**Review by sanders41 — APPROVED** [review]

**Comment by adamsachs** [comment]
@ThomasLaPiana maybe you'd like to give this a quick look based on the 2.4.0 release process you went through? once you've taken a look and added/changed anything you think is needed, then i think we should be good to merge this in.

**Review by ThomasLaPiana — APPROVED** [review]

**Comment by ThomasLaPiana** [comment]
@adamsachs coincidentally I added some myself yesterday as well! good updates here :) 

the checklist should be as simple to follow as possible

**Pull request merged**
