### PR TITLE
Add "generate" & "scan" to the local commands

### LINKED ISSUE #840: Local mode (`--local`) doesn't seem to allow using the `fidesctl generate` commands
### Bug Description

I was wanting to use `fidesctl` to generate a YAML without spinning up the webserver locally, and figured I'd take `--local` mode for a spin as I hadn't used it recently.

Unfortunately, I think `--local` doesn't disable the reliance on API like we thought anymore, as I immediately get errors:
```
$ fidesctl --local generate dataset db foo
Connection failed, webserver is unreachable at URL:
http://localhost/api/v1/health.
```

#### Steps to Reproduce

```
~% mkdir ~/fidesctl-local-test
~% cd fidesctl-local-test
~/fidesctl-local-test% python3 -m venv venv
~/fidesctl-local-test% ./venv/bin/pip install fidesctl
...
~/fidesctl-local-test% ./venv/bin/fidesctl --local generate db foo
No config file found
Using default configuration values.
Connection failed, webserver is unreachable at URL:
http://localhost/api/v1/health.
```

### Expected behavior

I'd like as many of the CLI commands as possible to work without the webserver - but especially commands like `generate`, `scan` and similar that are meant to help me author my YAML files 👍 

### Environment

* Version: 1.7.0
* OS: macOS-12.4-x86_64-i386-64bit
* Python Version: 3.10.5
* Docker Version: 20.10.11

```
~/fidesctl-local-test% ./venv/bin/fidesctl --version
fidesctl, version 1.7.0
~/fidesctl-local-test% ./venv/bin/python --version
Python 3.10.5
~/fidesctl-local-test% ./venv/bin/python -m platform
macOS-12.4-x86_64-i386-64bit
~/fidesctl-local-test% docker --version
Docker version 20.10.11, build dea9396
```

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #840 

### Code Changes

* [x] move `generate` from API to Local commands
* [x] move `scan` from API to Local commands
* [x] update `cli_docs` to be a `deepcopy` so that it doesn't affect the cli help message

### Steps to Confirm

* [ ] `fidesctl --local` shows the correct commands (including `scan` and `generate`)
* [ ] auto-generated CLI docs function as they did before

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  - [x] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  - [ ] documentation issue created (tag docs-team to complete issue separately)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`

### Description Of Changes

Quick change here that moves `scan` and `generate` to the `--local` command list and also fixes a bug that would show API commands in the help message even when passing in the `--local` flag

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
Fix shown here:

## With the local flag
```
fides> fidesctl --local
Usage: fidesctl [OPTIONS] COMMAND [ARGS]...

  The parent group for the Fidesctl CLI.

Options:
  --version               Show the version and exit.
  -f, --config-path TEXT  Path to a configuration file.
                          Use 'fidesctl view-config' to
                          print the config. Not
                          compatible with the 'fidesctl
                          webserver' subcommand.
  --local                 Run in 'local_mode'. This mode
                          doesn't make API calls and can
                          be used without the API
                          server/database.
  -h, --help              Show this message and exit.

Commands:
  evaluate   Compare your System's Privacy...
  generate   Generate fidesctl resource types
  init       Initializes a Fidesctl instance,...
  parse      Reads the resource files that are...
  scan       Scan external resource coverage against...
  view       View various resources types.
  webserver  Starts the fidesctl API server using...
```

## Without the local flag
```
fides> fidesctl        
Usage: fidesctl [OPTIONS] COMMAND [ARGS]...

  The parent group for the Fidesctl CLI.

Options:
  --version               Show the version and exit.
  -f, --config-path TEXT  Path to a configuration file.
                          Use 'fidesctl view-config' to
                          print the config. Not
                          compatible with the 'fidesctl
                          webserver' subcommand.
  --local                 Run in 'local_mode'. This mode
                          doesn't make API calls and can
                          be used without the API
                          server/database.
  -h, --help              Show this message and exit.

Commands:
  annotate   Annotate fidesctl resource types
  apply      Validate local manifest files and...
  db         Database utility commands
  delete     Delete a resource on the server.
  evaluate   Compare your System's Privacy...
  export     Export fidesctl resource types
  generate   Generate fidesctl resource types
  get        View a resource from the server as a...
  init       Initializes a Fidesctl instance,...
  ls         Get a list of all resources of this...
  parse      Reads the resource files that are...
  scan       Scan external resource coverage against...
  status     Sends a request to the Fidesctl API...
  sync       Update local resource files by their...
  view       View various resources types.
  webserver  Starts the fidesctl API server using...
```

**Comment by ThomasLaPiana** [comment]
i've actually hit a bug here, will update with my findings later

**Comment by ThomasLaPiana** [comment]
fixed by editing the `commands` attribute directly on the `cli` object

**Review by SteveDMurphy — APPROVED** [review]
Tested out and looks good to me! Nice bonus with cleaning up the separate `cli_docs` command 👍🏽

**Pull request merged**
