### PR TITLE
Add the TOC to the Nav Sidebar

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes <issue>

### Code Changes

* [x] move the table of contents to the sidebar nav instead of the right-hand side

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Documentation Updated
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created

### Description Of Changes

This small change moves the TOC to be embedded within the sidebar nav instead of on the opposite side as its own thing

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
@conceptualshark would love to get your opinion here! Trying to decide which one looks better 🤔

**Comment by ThomasLaPiana** [comment]
## New:

left_toc

## Old:

right_toc

**Comment by iamkelllly** [comment]
Pinging @conceptualshark and @suchiroll to review this, we're looking to have the TOC styling standardizing across all repos. Personal preference is to keep the page-level TOC on the right side as moving it into the left nav makes the left nav too long and decreases its overall readability/scannability. Open to thoughts here though so we can make a decision quickly here

**Comment by conceptualshark** [comment]
I agree that New feels more intuitive structurally, but does it actually do what we want? I think that leaving this on the right for now (old) leaves more room to grow and restructure the current-state docs. Curious how something like the the auto-generated CLI docs would look with this, as an extreme example. 

I think we'd be better off utilizing the existing toc better (via site and page structure, headers, etc) to highlight the fact that the toc exists in the first place. The [mkdocs material](https://squidfunk.github.io/mkdocs-material/getting-started/) site uses the default theme pretty effectively.

**Pull request closed without merging**
