### PR TITLE
Update frontend npm packages (admin-ui, privacy-center, cypress-e2e)

### PR DESCRIPTION
**Pull request by NevilleS**
### Code Changes

* [X] First, use `npm update` to "safely" upgrade based on semver, etc
* [X] Next, use the `npm-check-updates` utility to selectively upgrade dependencies to latest versions, where it felt reasonable
* [X] Last, use `npx depcheck` to find unused dependencies and `npm uninstall` them

### Steps to Confirm

* [X] Run all automated tests (`npm test`, `npm run cy:run`)
* [x] Run all CI checks
* [x] Manual smoke tests with `nox -s "fides_env(test)"`

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* Documentation:
  * [x] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [x] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`
* [x] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### Description Of Changes

It felt like some spring cleaning was in order, especially as we look towards some major new features in the Admin UI. This is a sweeping update of our frontend dependencies including some major version upgrades to packages like `react-redux`, `eslint`, etc.

The packages I avoided here that require more careful consideration are `react`, `next`, `chakra-ui`, and `typescript`. Some of these will likely need code migrations or breaking changes, so I didn't attempt those upgrades.

### CODE REVIEW

**Comment by TheAndrewJackson** [comment]
I got one failure when running `npm run cy:run`

Screenshot 2023-03-28 at 12 38 06

User Authentication -- when the user is logged in -- lets them log out (failed) (attempt 2)



Building and checking `nox -s "fides_env(test)"` now

**Comment by NevilleS** [comment]
That's a bit odd, because that definitely runs as part of the CI checks. Let me know what you find

**Comment by TheAndrewJackson** [comment]
I was able to logout with the test build. I think it's probably just a flaky test. If you're not seeing/rarely seeing that failure locally I'm comfortable with merging this

**Comment by NevilleS** [comment]
OK thanks- drop a review here, I'm re-running `cy:run` myself once more for good measure, but I think it's ship time

**Comment by NevilleS** [comment]
(Side note, and maybe related... one dependency I _didn't_ update to latest was `eslint-plugin-cypress` which literally released a new version a few hours ago that triggered a bunch of lint errors in our Cypress tests for "unsafe chain commands". Maybe that delinting could help... but I don't want to keep boiling the ocean here so I'm going to ship with the older linter today)

**Pull request merged**
