### PR TITLE
OneSignal Connector

### LINKED ISSUE #1324: OneSignal

### PR DESCRIPTION
**Pull request by tmuralikrishnan**
Closes #1324

### Code Changes
NEW SaaS Connector OneSignal for access and erasure 

### Steps to Confirm
* [x] Add/configure the OneSignal connector in UI
* [x] Verify OneSignal config and icon UI looks good 
* [x] Add customer data using OneSignal API 
* [x] Create an Access DSR with the new OneSignal customer email 
* [x] Verify email sent by fides with customer data is correct 
* [x] Create an update DSR with the new OneSignal customer email 
* [x] Verify the customer data is now updated in OneSignal

### Pre-Merge Checklist
* [ ] All CI Pipelines Succeeded
* [ ] Update `CHANGELOG.md`

### SaaS Connector Checklist 
* [x] [Spec doc link]()
* [x] Vault Creds
* [x] Postman Collection
* [x] SaaS Config And Dataset 
* [x] Access and Erasure Tests Passing 
* [x] Icon

### CODE REVIEW

**Comment by ctvivek** [comment]
Screenshot from 2023-03-03 00-20-12

**Comment by ctvivek** [comment]
Screenshot from 2023-03-03 00-30-56

**Comment by ctvivek** [comment]
Screenshot from 2023-03-02 21-34-48

**Comment by ctvivek** [comment]
Screenshot from 2023-03-03 00-20-12

**Comment by ctvivek** [comment]
Screenshot from 2023-03-03 12-14-01

**Comment by ctvivek** [comment]
Screenshot from 2023-03-03 12-16-44

**Comment by ctvivek** [comment]
Screenshot from 2023-03-07 11-44-41

**Comment by ctvivek** [comment]
Screenshot from 2023-03-07 11-45-00

**Comment by ctvivek** [comment]
Screenshot from 2023-03-07 11-47-10

**Review by galvana — CHANGES_REQUESTED** [review]
We need to go back to the spec phase for this connector. OneSignal recommends using an `external_id` so that should be used as our `external_reference` instead of hard-coding a `player_id` and `app_id` @Kelsey-Ethyca

**Pull request closed without merging**
