### PR TITLE
Add timeouts for CLI checks

### LINKED ISSUE #1680: `fides deploy` CI test can run indefinitely
### Bug Description

Sometimes the `fides deploy` CI job will run indefinitely instead of failing.

Add a time limit to it to prevent this

### PR DESCRIPTION
**Pull request by ThomasLaPiana**
Closes #1680 

### Code Changes

* [x] add a 15-minute timeout to the `test_env` and `fides deploy` jobs

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

Quick PR to prevent indefinite jobs from wasting CI minutes and covering up errors

### CODE REVIEW

**Comment by ThomasLaPiana** [comment]
the `fides deploy` step timed out as expected, merging as complete

**Comment by seanpreston** [comment]
@ThomasLaPiana if we're expecting that job to timeout every time, why are we running it as part of the CI?

**Comment by ThomasLaPiana** [comment]
@seanpreston we are not expecting it to time out every time, it should be succeeding or failing, but it seems to fail by running indefinitely sometimes so this is a protection against forever-running CI jobs

**Comment by ThomasLaPiana** [comment]
ideally we would figure out _why_ it's timing out when it fails but for now this hasn't been prioritized

**Pull request merged**
