### PR TITLE
Include base64 encoded icon image data in connection_type response

### LINKED ISSUE #1231: update `connection_type` endpoint to include encoded logo image data in response payload
### Is your feature request related to a specific problem?

With https://github.com/ethyca/fides/pull/1197, we made the `type` on a SaaS config dynamic, and got rid of the enum constraint on that field, to allow for more flexible and dynamic creation of saas connectors.

The frontend, though, still essentially treats SaaS types as an enum. One significant piece of that is looking up the logo image for the given SaaS type. We are already returning SaaS type information dynamically via the `api/v1/connection_type` endpoint, and we already have the path to the logo image information populated "dynamically" on the backend, so we should just include encoded logo image binary in our response payload so that the front end can render the images dynamically.

### Describe the solution you'd like

- Update the `api/v1/connection_type` endpoint to include encoded image logo binary for each record of a saas type that's returned
    - We'll also probably want to update the endpoint to include something similar for non-saas connection types (db, manual)

### Additional context

- Generally part of an effort to make the frontend more robust/dynamic in its handling of saas connector types

### PR DESCRIPTION
**Pull request by adamsachs**
Closes #1231 

Follow up ticket for front-end work is: https://github.com/ethyca/fides/issues/1413

### Steps to Confirm

* [ ] _list any manual steps taken to confirm the changes_

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation Updated:
  * [ ] documentation complete, or draft/outline provided (tag docs-team to complete/review on this branch)
  * [ ] documentation issue created (tag docs-team to complete issue separately)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [ ] Update `CHANGELOG.md`

### Description Of Changes

* Adds `encoded_image` field to the response body schema of `api/v1/connection_types`, and the field includes a base64 encoded image binary for the connector's icon image. 
* The field is currently only populated for SaaS connectors; other connectors have `None` for the field.
* Sample response payload: [sample_response_encoded_icon_base64.json.txt](https://github.com/ethyca/fides/files/9766824/sample_response_encoded_icon_base64.json.txt) (github doesn't seem to allow `.json` uploads...)

### CODE REVIEW

**Comment by sanders41** [comment]
The code looks good to me. I just have a general question. Sometimes the icon is `null` and sometimes it defaults to the Ethyca thumbprint logo. Should we default all of the ones that don't have an icon to that?

**Comment by adamsachs** [comment]
> Sometimes the icon is null and sometimes it defaults to the Ethyca thumbprint logo. Should we default all of the ones that don't have an icon to that?

yeah, i thought about that a bit, it's a good question. currently, only for SaaS connectors do we have knowledge of icon images on the backend (even though without this PR, it's not really used anywhere afaik); for non-saas connectors, it's totally on the front-end. the motivation for this PR is to enable more rapid SaaS connector development, and therefore to allow a backend developer to add a new saas connector, "register" the icon image on the backend, and then it's served up in the UI automatically. there doesn't need to be such a dynamic workflow for the non-saas connectors, since they're not developed so rapidly.

updating the backend code such that non-saas connectors now refer to icon images seemed to expand scope of this PR more than i wanted. so i was anticipating the front-end logic, for now, would look at the `encoded_icon` field in the response, and if it's `None`, then it would default to essentially the same logic it has now.

i'm open to other ideas on this though - i don't love where it's ended up, but i don't see anything terribly inconsistent, and the updates here were pretty straightforward.

**Review by sanders41 — APPROVED** [review]
I'm good with this answer if it works for @chriscalhoun1974. We could always do a follow-up PR if we decide it makes sense to default them all.

**Comment by chriscalhoun1974** [comment]
@sanders41 @adamsachs I have the following questions:

1. For non Saas connection types, the FE will continue to render the existing static asset .svg accordingly? Otherwise if it's a Saas connection type, reference the `encoded_icon` attribute?

2. In addition, when referencing the `encoded_icon` attribute for UI rendering purposes, I will need to append `data:image/svg+xml;base64,` as a prefix to the `encoded_icon` value? My assumption is yes.

**Comment by adamsachs** [comment]
> For non Saas connection types, the FE will continue to render the existing static asset .svg accordingly? Otherwise if it's a Saas connection type, reference the encoded_icon attribute?

yes, that's what i was thinking, generally. i would maybe suggest just looking at the `encoded_icon` attribute and rendering if it's populated (vs being `None`), rather than relying on whether the connection type is `SaaS ` or not, just to make the code a bit more future-proofed if/when we decide to pass back image data for non-SaaS types in the future. but if that doesn't make sense in the context of the FE codebase, then as you suggested should work just fine for now.

> In addition, when referencing the encoded_icon attribute for UI rendering purposes, I will need to append data:image/svg+xml;base64, as a prefix to the encoded_icon value? My assumption is yes.

i believe that's correct (per our previous conversations). i'll attach a sample response payload to the PR here for clarity. also for additional context, @sanders41 and i looked into whether our fastapi/pydantic gives us a way to more formally indicate that the field in the response model is actually encoded bytes - and we were unable to find anything. specifically, there seems to be an open pydantic issue https://github.com/pydantic/pydantic/issues/692 for exactly what we're looking for here (been open for around 2 years!)

**Pull request merged**
