### PR TITLE
update to latest `asyncpg` dependency

### LINKED ISSUE #3613: `asyncpg==0.25.0` is causing build errors
### Bug Description

- https://github.com/pypa/setuptools/pull/3948 updates `setuptools` to no longer ignore "invalid pyproject.toml: when pyproject.toml was introduced there were some people writing invalid files" ; i.e., essentially there'd been a grace period in place to allow technically invalid `pyproject.toml`s, and that grace period is now over
    - `fides` images have a build step that updates `setuptools` to use the [latest release](https://github.com/pypa/setuptools/releases/tag/v68.0.0), which seems to include this update to remove the grace period
- `asyncpg` had this type of invalid pyproject.toml, they [resolved it](https://github.com/MagicStack/asyncpg/releases/tag/v0.26.0) in 0.26.0 , but we're pinned to `asyncpg==0.25.0` (hence why unpinning `asyncpg` in our `requirements.txt` works well to resolve!)
- i think we can just upgrade our `asyncpg` dependency, hopefully without regressions 🤞

#### Steps to Reproduce

- run `nox -s dev` on `main` and you should get the following build time error:
```
#12 1.018   Installing build dependencies: started
#12 2.126   Installing build dependencies: finished with status 'done'
#12 2.127   Getting requirements to build wheel: started
#12 2.223   Getting requirements to build wheel: finished with status 'error'
#12 2.226   error: subprocess-exited-with-error
#12 2.226
#12 2.226   × Getting requirements to build wheel did not run successfully.
#12 2.226   │ exit code: 1
#12 2.226   ╰─> [28 lines of output]
#12 2.226       Traceback (most recent call last):
#12 2.226         File "/opt/fides/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#12 2.226           main()
#12 2.226         File "/opt/fides/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#12 2.226           json_out['return_val'] = hook(**hook_input['kwargs'])
#12 2.226         File "/opt/fides/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#12 2.226           return hook(config_settings)
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
#12 2.226           return self._get_build_requires(config_settings, requirements=['wheel'])
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
#12 2.226           self.run_setup()
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
#12 2.226           exec(code, locals())
#12 2.226         File "<string>", line 248, in <module>
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
#12 2.226           return distutils.core.setup(**attrs)
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
#12 2.226           dist.parse_config_files()
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 898, in parse_config_files
#12 2.226           pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
#12 2.226           config = read_configuration(filepath, True, ignore_option_errors, dist)
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 128, in read_configuration
#12 2.226           validate(subset, filepath)
#12 2.226         File "/tmp/pip-build-env-k3z2s7ho/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
#12 2.226           raise ValueError(f"{error}\n{summary}") from None
#12 2.226       ValueError: invalid pyproject.toml config: `project`.
#12 2.226       configuration error: `project` must contain ['name'] properties
#12 2.226       [end of output]
#12 2.226
#12 2.226   note: This error originates from a subprocess, and is likely not a problem with pip.
#12 2.227 error: subprocess-exited-with-error
#12 2.227
#12 2.227 × Getting requirements to build wheel did not run successfully.
#12 2.227 │ exit code: 1
#12 2.227 ╰─> See above for output.
#12 2.227
#12 2.227 note: This error originates from a subprocess, and is likely not a problem with pip.
------
executor failed running [/bin/sh -c pip install --no-cache-dir install -r requirements.txt]: exit code: 1
nox > Command docker build --target=dev --tag ethyca/fides:local . failed with exit code 1
nox > Session dev failed.
```

### Expected behavior

our build should work 😄 

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

- [here](https://github.com/pypa/setuptools/issues/3199) is the original `setuptools` GH issue that allowed me to gather most of this info

### PR DESCRIPTION
**Pull request by adamsachs**
Closes #3613 

### Code Changes

* [ ] update to latest `asyncpg` dependency to avoid build error

### Steps to Confirm

* [ ] our images build
* [ ] no regressions (🤞 for good automated test coverage!)

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* Documentation:
  * [ ] documentation complete, [PR opened in fidesdocs](https://github.com/ethyca/fidesdocs/pulls)
  * [ ] documentation [issue created in fidesdocs](https://github.com/ethyca/fidesdocs/issues/new/choose)
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`
* [ ] For API changes, the [Postman collection](https://github.com/ethyca/fides/blob/main/docs/fides/docs/development/postman/Fides.postman_collection.json) has been updated

### Description Of Changes

See issue description for a synopsis of why this is just now biting us, it's been lurking for a while!

### CODE REVIEW

**Comment by adamsachs** [comment]
this is obviously a straightforward change to get us past a build error. 

@ThomasLaPiana and @pattisdr just figured you two would be the best suited to know whether updating `asyncpg` could have some hidden issue, and @allisonking you reported this so also wanted to make sure it looked alright to you!

**Review by SteveDMurphy — APPROVED** [review]
Fixed the build error for me! Thanks @adamsachs

**Comment by pattisdr** [comment]
Also verified that this fixed things, thanks for your work here!

**Comment by vittoriozamboni** [comment]
Thanks @adamsachs , I had this error in another project and took me a while to get it was asyncpg.

**Pull request merged**
